# Generated by Django 4.0.5 on 2025-06-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='otp',
        ),
    ]
