# Generated by Django 4.0.5 on 2025-06-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_authentication_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='phone_number',
        ),
    ]
