# Generated by Django 4.0.5 on 2025-06-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_authentication_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='email',
            field=models.CharField(default='admin@email.com', max_length=255),
            preserve_default=False,
        ),
    ]
