# Generated by Django 4.0.5 on 2024-06-15 06:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEnquiry',
            fields=[
                ('key', models.AutoField(db_column='CustEnq_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, db_column='CustEnq_ID', max_length=30, null=True)),
                ('name', models.CharField(blank=True, db_column='CustEnq_Name', max_length=30, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='CustEnq_PhoneNumber', max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank=True, db_column='CustEnq_Address', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='CustEnq_City', max_length=30, null=True)),
                ('state', models.CharField(blank=True, db_column='CustEnq_State', max_length=30, null=True)),
                ('comments', models.CharField(blank=True, db_column='CustEnq_Comments', max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='CustEnq_Date', null=True)),
                ('client_id', models.ForeignKey(db_column='CustEnq_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='CustEnq_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('project1', models.ForeignKey(blank=True, db_column='CustEnq_Project1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project1', to='project.project')),
                ('project2', models.ForeignKey(blank=True, db_column='CustEnq_Project2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project2', to='project.project')),
                ('project3', models.ForeignKey(blank=True, db_column='CustEnq_Project3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project3', to='project.project')),
            ],
            options={
                'db_table': 'Customer_Enquiry',
                'managed': True,
            },
        ),
    ]
