# Generated by Django 4.0.5 on 2025-02-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerEnquiry',
        ),
    ]
