# Generated by Django 4.0.5 on 2025-02-03 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0012_alter_project_unique_together_remove_project_id'),
        ('client', '0002_bankaccount'),
        ('leads', '0002_delete_customerenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpStatus',
            fields=[
                ('key', models.AutoField(db_column='FollowUpStatus_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='FollowUpStatus_Name', max_length=100)),
            ],
            options={
                'db_table': 'FollowUpStatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('key', models.AutoField(db_column='Lead_Key', primary_key=True, serialize=False)),
                ('lead_no', models.CharField(db_column='Lead_No', max_length=10)),
                ('lead_name', models.CharField(blank=True, db_column='Lead_Name', max_length=255, null=True)),
                ('enquiry_date', models.DateField(blank=True, db_column='Lead_EnquiryDate', null=True)),
                ('contact_1', models.CharField(db_column='Lead_Contact1', max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^\\+?1?\\d{9,15}$')])),
                ('contact_2', models.CharField(blank=True, db_column='Lead_Contact2', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^\\+?1?\\d{9,15}$')])),
                ('budget', models.IntegerField(db_column='Lead_Budget')),
                ('budget_range', models.IntegerField(db_column='Lead_BudgetRange')),
                ('email', models.CharField(blank=True, db_column='Lead_Email', max_length=100, null=True)),
                ('property_interest', models.CharField(db_column='Lead_PrprtyInt', max_length=255)),
                ('source', models.CharField(db_column='Lead_Source', max_length=255)),
                ('createdby', models.CharField(blank=True, db_column='Lead_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='Lead_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='Lead_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='Lead_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='Lead_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='Lead_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'db_table': 'Lead',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('key', models.AutoField(db_column='LeadStatus_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='LeadStatus_Name', max_length=100)),
            ],
            options={
                'db_table': 'LeadStatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('key', models.AutoField(db_column='VisitStatus_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='VisitStatus_Name', max_length=100)),
            ],
            options={
                'db_table': 'VisitStatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('key', models.AutoField(db_column='Visit_Key', primary_key=True, serialize=False)),
                ('visit_date', models.DateField(db_column='Visit_Date')),
                ('agent_name', models.CharField(db_column='Visit_AgentName', max_length=255)),
                ('agent_phone', models.CharField(db_column='Visit_AgentPhone', max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^\\+?1?\\d{9,15}$')])),
                ('createdby', models.CharField(blank=True, db_column='Visit_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='Visit_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='Visit_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='Visit_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='Visit_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='Visit_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('lead_key', models.ForeignKey(db_column='Visit_LeadKey', on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('project_key', models.ForeignKey(db_column='Visit_ProjKey', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('status_key', models.ForeignKey(db_column='Visit_StatusKey', on_delete=django.db.models.deletion.CASCADE, to='leads.visitstatus')),
            ],
            options={
                'db_table': 'Visit',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='status_key',
            field=models.ForeignKey(db_column='Lead_StatusKey', on_delete=django.db.models.deletion.CASCADE, to='leads.leadstatus'),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('key', models.AutoField(db_column='FollowUp_Key', primary_key=True, serialize=False)),
                ('days_since_enquiry', models.IntegerField(db_column='FollowUp_DaysSinceEnq')),
                ('last_followup_date', models.DateField(db_column='FollowUp_LastFlwUpDate')),
                ('follow_notes', models.CharField(db_column='FollowUp_Notes', max_length=255)),
                ('createdby', models.CharField(blank=True, db_column='FollowUp_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='FollowUp_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='FollowUp_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='FollowUp_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='FollowUp_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='FollowUp_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('employee_key', models.ForeignKey(db_column='FollowUp_EmpKey', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead_key', models.ForeignKey(db_column='FollowUp_LeadKey', on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('status_key', models.ForeignKey(db_column='FollowUp_StatusKey', on_delete=django.db.models.deletion.CASCADE, to='leads.followupstatus')),
            ],
            options={
                'db_table': 'FollowUp',
                'managed': True,
            },
        ),
    ]
