# Generated by Django 4.0.5 on 2025-02-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('leads', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupstatus',
            name='client_id',
            field=models.ForeignKey(db_column='FollowUpStatus_Client_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.clientbase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followupstatus',
            name='company_id',
            field=models.ForeignKey(db_column='FollowUpStatus_Company_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='client_id',
            field=models.ForeignKey(db_column='LeadStatus_Client_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.clientbase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='company_id',
            field=models.ForeignKey(db_column='LeadStatus_Company_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitstatus',
            name='client_id',
            field=models.ForeignKey(db_column='VisitStatus_Client_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.clientbase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitstatus',
            name='company_id',
            field=models.ForeignKey(db_column='VisitStatus_Company_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.company'),
            preserve_default=False,
        ),
    ]
