# Generated by Django 4.0.5 on 2025-05-04 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0004_followupstatus_client_id_followupstatus_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='days_since_enquiry',
            field=models.IntegerField(blank=True, db_column='FollowUp_DaysSinceEnq', null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='employee_key',
            field=models.ForeignKey(blank=True, db_column='FollowUp_EmpKey', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_notes',
            field=models.CharField(blank=True, db_column='FollowUp_Notes', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='last_followup_date',
            field=models.DateField(db_column='FollowUp_Date'),
        ),
    ]
