# Generated by Django 4.0.5 on 2025-05-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_followup_days_since_enquiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('key', models.AutoField(db_column='Comments_Key', primary_key=True, serialize=False)),
                ('related_key', models.IntegerField(blank=True, db_column='Comments_RelatedKey', null=True)),
                ('comment_type', models.CharField(blank=True, choices=[('Lead', 'Lead'), ('FollowUp', 'FollowUp'), ('Visit', 'Visit')], db_column='Comments_Type', max_length=20, null=True)),
                ('comment', models.TextField(db_column='Comments_Comment')),
                ('createdby', models.CharField(blank=True, db_column='Comments_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='Comments_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='Comments_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='Comments_LastModifiedDtTm', null=True)),
            ],
            options={
                'db_table': 'CRMComments',
                'managed': True,
            },
        ),
    ]
