# Generated by Django 4.0.5 on 2025-05-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.IntegerField(blank=True, db_column='Lead_Budget', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget_range',
            field=models.IntegerField(blank=True, db_column='Lead_BudgetRange', null=True),
        ),
    ]
