# Generated by Django 4.0.5 on 2025-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_budget_alter_lead_budget_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='followup_time',
            field=models.CharField(db_column='FollowUp_Time', default='10:22 AM', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_time',
            field=models.CharField(db_column='Visit_Time', default='10:22 AM', max_length=20),
            preserve_default=False,
        ),
    ]
