# Generated by Django 4.0.5 on 2026-01-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('leads', '0008_followup_followup_time_visit_visit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancies',
            fields=[
                ('key', models.AutoField(db_column='Occupancies_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='Occupancies_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='Occupancies_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'Occupancies',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='lead',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='property_interest',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.CreateModel(
            name='ProjectInterests',
            fields=[
                ('key', models.AutoField(db_column='ProjectInt_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='ProjectInt_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='ProjectInt_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'ProjectInterests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OccupancySubTypes',
            fields=[
                ('key', models.AutoField(db_column='OccupancySubTyp_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='OccupancySubTyp_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='OccupancySubTyp_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('occup_id', models.ForeignKey(blank=True, db_column='OccupancySubTyp_Occup_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.occupancies')),
            ],
            options={
                'db_table': 'OccupancySubTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocationPreference',
            fields=[
                ('key', models.AutoField(db_column='LocationPref_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='LocationPref_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='LocationPref_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'LocationPreference',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeadSourceCategory',
            fields=[
                ('key', models.AutoField(db_column='LeadSourceCtgry_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='LeadSourceCtgry_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='LeadSourceCtgry_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'LeadSourceCategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('key', models.AutoField(db_column='LeadSource_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='LeadSource_Descr', max_length=100)),
                ('category_id', models.ForeignKey(db_column='LeadSource_Ctgry_ID', on_delete=django.db.models.deletion.CASCADE, to='leads.leadsourcecategory')),
                ('client_id', models.ForeignKey(db_column='LeadSource_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'LeadSource',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeadLocationPreference',
            fields=[
                ('key', models.AutoField(db_column='LeadLocPref_Key', primary_key=True, serialize=False)),
                ('client_id', models.ForeignKey(db_column='LeadLocPref_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='LeadLocPref_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('lead_key', models.ForeignKey(blank=True, db_column='LeadLocPref_Lead_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('locationpref_key', models.ForeignKey(blank=True, db_column='LeadLocPref_LeadPref_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.locationpreference')),
            ],
            options={
                'db_table': 'LeadLocationPreferance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FollowUpStages',
            fields=[
                ('key', models.AutoField(db_column='FollowUpStages_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='FollowUpStages_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='FollowUpStages_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'FollowUpStages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FloorPreference',
            fields=[
                ('key', models.AutoField(db_column='FloorsPref_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='FloorsPref_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='FloorsPref_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'FloorsPreference',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacingPreference',
            fields=[
                ('key', models.AutoField(db_column='FacingPref_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='FacingPref_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='FacingPref_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'FacingPreference',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BudgetRanges',
            fields=[
                ('key', models.AutoField(db_column='BudgetRanges_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='BudgetRanges_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='BudgetRanges_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'BudgetRanges',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='budget_rng_key',
            field=models.ForeignKey(blank=True, db_column='Lead_BudgetRng_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.budgetranges'),
        ),
        migrations.AddField(
            model_name='lead',
            name='facing_pref_key',
            field=models.ForeignKey(blank=True, db_column='Lead_FacingPref_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.facingpreference'),
        ),
        migrations.AddField(
            model_name='lead',
            name='floor_pref_key',
            field=models.ForeignKey(blank=True, db_column='Lead_FloorPref_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.floorpreference'),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_upstg_key',
            field=models.ForeignKey(blank=True, db_column='Lead_FollowUpStg_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.followupstages'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_src_ctgry_key',
            field=models.ForeignKey(blank=True, db_column='Lead_LeadSrcCtgry_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leadsourcecategory'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_src_key',
            field=models.ForeignKey(blank=True, db_column='Lead_LeadSrc_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leadsource'),
        ),
        migrations.AddField(
            model_name='lead',
            name='occupa_subtyp_key',
            field=models.ForeignKey(blank=True, db_column='Lead_OccupaSubTyp_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.occupancysubtypes'),
        ),
        migrations.AddField(
            model_name='lead',
            name='occupancies_key',
            field=models.ForeignKey(blank=True, db_column='Lead_Occupancies_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.occupancies'),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_interest_key',
            field=models.ForeignKey(blank=True, db_column='Lead_PrprtyInt_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.projectinterests'),
        ),
    ]
