# Generated by Django 4.0.5 on 2026-01-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0039_project_no_of_blocks_alter_projectblock_lift_count_and_more'),
        ('leads', '0009_occupancies_remove_lead_budget_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadProjectPreference',
            fields=[
                ('key', models.AutoField(db_column='LeadProjectPref_Key', primary_key=True, serialize=False)),
                ('client_id', models.ForeignKey(db_column='LeadProjectPref_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='LeadProjectPref_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('lead_key', models.ForeignKey(blank=True, db_column='LeadProjectPref_Lead_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('project_key', models.ForeignKey(blank=True, db_column='LeadProjectPref_Proj_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'LeadProjectPreference',
                'managed': True,
            },
        ),
    ]
