# Generated by Django 4.0.5 on 2026-01-25 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_project_no_of_blocks_alter_projectblock_lift_count_and_more'),
        ('client', '0002_bankaccount'),
        ('leads', '0010_leadprojectpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('key', models.AutoField(db_column='Feedback_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='Feedback_Descr', max_length=255)),
                ('client_id', models.ForeignKey(db_column='Feedback_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'Feedback',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='followup',
            name='status_key',
            field=models.ForeignKey(blank=True, db_column='FollowUp_StatusKey', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.followupstatus'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='agent_name',
            field=models.CharField(blank=True, db_column='Visit_AgentName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='agent_phone',
            field=models.CharField(blank=True, db_column='Visit_AgentPhone', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='project_key',
            field=models.ForeignKey(blank=True, db_column='Visit_ProjKey', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.CreateModel(
            name='FeedBackDetails',
            fields=[
                ('key', models.AutoField(db_column='FeedBackDetails_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='FeedBackDetails_Descr', max_length=255)),
                ('client_id', models.ForeignKey(db_column='FeedBackDetails_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('feedback_id', models.ForeignKey(blank=True, db_column='FeedBackDetails_Feedback_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.feedback')),
            ],
            options={
                'db_table': 'FeedBackDetails',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='followup',
            name='feedback_key',
            field=models.ForeignKey(blank=True, db_column='FollowUp_Feedback_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.feedback'),
        ),
        migrations.AddField(
            model_name='followup',
            name='followup_details_key',
            field=models.ForeignKey(blank=True, db_column='FollowUp_FeedbackDetails_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.feedbackdetails'),
        ),
    ]
