# Generated by Django 4.0.5 on 2026-02-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('leads', '0011_feedback_alter_followup_status_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='facing_pref_key',
        ),
        migrations.CreateModel(
            name='LeadFacingPreference',
            fields=[
                ('key', models.AutoField(db_column='LeadFacingPref_Key', primary_key=True, serialize=False)),
                ('client_id', models.ForeignKey(db_column='LeadFacingPref_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='LeadFacingPref_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('facingpref_key', models.ForeignKey(blank=True, db_column='LeadFacingPref_FacingPref_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.facingpreference')),
                ('lead_key', models.ForeignKey(blank=True, db_column='LeadFacingPref_Lead_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'db_table': 'LeadFacingPreference',
                'managed': True,
            },
        ),
    ]
