# Generated by Django 4.0.5 on 2026-02-11 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_remove_lead_facing_pref_key_leadfacingpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_1',
            field=models.CharField(db_column='Lead_Contact1', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
