# Generated by Django 4.0.5 on 2026-02-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_lead_contact_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_notes',
            field=models.CharField(blank=True, db_column='FollowUp_Notes', max_length=500, null=True),
        ),
    ]
