# Generated by Django 4.0.5 on 2026-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_followup_follow_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_no',
            field=models.CharField(db_column='Lead_No', max_length=10, unique=True),
        ),
    ]
