INSERT INTO "builder-iq"."Company" ("Company_Name", "Company_Client_ID")
VALUES
('Perfect Builders', '5'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('Testing11', '6'),
('this company for bussiness user purpose123', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('this company for bussiness user purpose', '6'),
('Dev Company', '4'),
('this company for bussiness user purpose', '6'),
('Sivarams Builders and Promotors Pvt Ltd', '9'),
('Test Company-updated 3', '1'),
('Test Company 2', '2'),
('Test Company 3', '3');