INSERT INTO "builder-iq"."State" ("State_Key", "State_ID", "State_Name")
VALUES
    (1, 'AP', 'Andhra Pradesh'),
    (2, 'AR', 'Arunachal Pradesham'),
    (3, 'AS', 'Assam'),
    (4, 'BR', 'Bihar'),
    (5, 'CG', 'Chhattisgarh'),
    (6, 'GA', 'Goa'),
    (7, 'GJ', 'Gujarat'),
    (8, 'HR', 'Haryana'),
    (9, 'HP', 'Himachal Pradesh'),
    (10, 'JK', 'Jammu and Kashmir'),
    (11, 'JH', 'Jharkhand'),
    (12, 'KA', 'Karnataka'),
    (13, 'KL', 'Kerala'),
    (14, 'MP', 'Madhya Pradesh'),
    (15, 'MH', 'Maharashtra'),
    (16, 'MN', 'Manipur'),
    (17, 'ML', 'Meghalaya'),
    (18, 'MZ', 'Mizoram'),
    (19, 'NL', 'Nagaland'),
    (20, 'OR', 'Orissa'),
    (21, 'PB', 'Punjab'),
    (22, 'RJ', 'Rajasthan'),
    (23, 'SK', 'Sikkim'),
    (24, 'TN', 'Tamil Nadu'),
    (25, 'TR', 'Tripura'),
    (26, 'UK', 'Uttarakhand'),
    (27, 'UP', 'Uttar Pradesh'),
    (28, 'WB', 'West Bengal'),
    (29, 'AN', 'Andaman and Nicobar Islands'),
    (30, 'CH', 'Chandigarh'),
    (31, 'DH', 'Dadra and Nagar Haveli'),
    (32, 'DD', 'Daman and Diu'),
    (33, 'DL', 'Delhi'),
    (34, 'LD', 'Lakshadweep'),
    (35, 'PY', 'Pondicherry');
