# Generated by Django 4.0.5 on 2024-06-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientbase',
            fields=[
                ('id', models.AutoField(db_column='Client_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Client_Name', max_length=100)),
            ],
            options={
                'db_table': 'ClientBase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(db_column='Company_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Company_Name', max_length=255)),
                ('client', models.ForeignKey(db_column='Company_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'Company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Costcategory',
            fields=[
                ('key', models.AutoField(db_column='CostCtg_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='CostCtg_ID', max_length=30)),
                ('descr', models.CharField(blank=True, db_column='CostCtg_Descr', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='CostCtg_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='CostCtg_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='CostCtg_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='CostCtg_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='CostCtg_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='CostCtg_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'db_table': 'CostCategory',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Costcode',
            fields=[
                ('key', models.AutoField(db_column='CostCd_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='CostCd_ID', max_length=30)),
                ('descr', models.CharField(blank=True, db_column='CostCd_Descr', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='CostCd_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='CostCd_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='CostCd_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='CostCd_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='CostCd_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='CostCd_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('costctg_key', models.ForeignKey(db_column='CostCd_CostCtg_Key', on_delete=django.db.models.deletion.CASCADE, to='client.costcategory')),
            ],
            options={
                'db_table': 'CostCode',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
    ]
