# Generated by Django 4.0.5 on 2024-07-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('key', models.AutoField(db_column='BankAccount_Key', primary_key=True, serialize=False)),
                ('acc_no', models.CharField(db_column='BankAccount_AccNo', max_length=50)),
                ('acc_name', models.CharField(db_column='BankAccount_AccName', max_length=255)),
                ('bank_name', models.CharField(db_column='BankAccount_BankName', max_length=255)),
                ('client_id', models.ForeignKey(db_column='BankAccount_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='BankAccount_CompanyID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'db_table': 'BankAccount',
                'managed': True,
            },
        ),
    ]
