# Generated by Django 4.0.5 on 2025-05-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('key', models.AutoField(db_column='WrkCtgry_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='WrkCtgry_Descr', max_length=255)),
                ('created_by', models.CharField(db_column='WrkCtgry_CreatedBy', max_length=255)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='WrkCtgry_CreatedDtTm')),
                ('lastmodified_by', models.CharField(blank=True, db_column='WrkCtgry_LastModifiedBy', max_length=255, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='WrkCtgry_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='WrkCtgry_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'WorkCategory',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('key', models.AutoField(db_column='WrkType_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='WrkType_Descr', max_length=255)),
                ('is_repetitive', models.BooleanField(db_column='WrkType_IsRepetitive')),
                ('created_by', models.CharField(db_column='WrkType_CreatedBy', max_length=255)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='WrkType_CreatedDtTm')),
                ('lastmodifiedby', models.CharField(blank=True, db_column='WrkType_LastModifiedBy', max_length=255, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='WrkType_LastModifiedDtTm', null=True)),
                ('category_key', models.ForeignKey(db_column='WrkType_Ctgry_Key', on_delete=django.db.models.deletion.CASCADE, to='estimate.workcategory')),
                ('client_id', models.ForeignKey(db_column='WrkType_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'WorkType',
            },
        ),
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('key', models.AutoField(db_column='WrkActivity_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='WrkActivity_Descr', max_length=255)),
                ('created_by', models.CharField(db_column='WrkActivity_CreatedBy', max_length=255)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='WrkActivity_CreatedDtTm')),
                ('lastmodifiedby', models.CharField(blank=True, db_column='WrkActivity_LastModifiedBy', max_length=255, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='WrkActivity_LastModifiedDtTm', null=True)),
                ('category_key', models.ForeignKey(db_column='WrkActivity_Ctgry_Key', on_delete=django.db.models.deletion.CASCADE, to='estimate.workcategory')),
                ('client_id', models.ForeignKey(db_column='WrkActivity_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('type_key', models.ForeignKey(db_column='WrkActivity_Type_Key', on_delete=django.db.models.deletion.CASCADE, to='estimate.worktype')),
            ],
            options={
                'db_table': 'WorkActivity',
            },
        ),
        migrations.CreateModel(
            name='MaterialPack',
            fields=[
                ('key', models.AutoField(db_column='MaterialPack_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='MaterialPack_Descr', max_length=255)),
                ('created_by', models.CharField(db_column='MaterialPack_CreatedBy', max_length=255)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='MaterialPack_CreatedDtTm')),
                ('lastmodifiedby', models.CharField(blank=True, db_column='MaterialPack_LastModifiedBy', max_length=255, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='MaterialPack_LastModifiedDtTm', null=True)),
                ('activity_key', models.ForeignKey(db_column='MaterialPack_Actvty_Key', on_delete=django.db.models.deletion.CASCADE, to='estimate.workactivity')),
                ('client_id', models.ForeignKey(db_column='MaterialPack_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'MaterialPack',
            },
        ),
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('key', models.AutoField(db_column='JobList_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='JobList_Descr', max_length=255)),
                ('created_by', models.CharField(db_column='JobList_CreatedBy', max_length=255)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='JobList_CreatedDtTm')),
                ('lastmodifiedby', models.CharField(blank=True, db_column='JobList_LastModifiedBy', max_length=255, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='JobList_LastModifiedDtTm', null=True)),
                ('activity_key', models.ForeignKey(db_column='JobList_Actvty_Key', on_delete=django.db.models.deletion.CASCADE, to='estimate.workactivity')),
                ('client_id', models.ForeignKey(db_column='JobList_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'JobList',
            },
        ),
    ]
