# Generated by Django 4.0.5 on 2024-06-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docid',
            name='client_id',
            field=models.ForeignKey(db_column='DocID_ClientID', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.clientbase'),
            preserve_default=False,
        ),
    ]
