# Generated by Django 4.0.5 on 2024-06-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('pricing', '0002_docid_client_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorinvoice',
            unique_together={('company', 'invoiceno')},
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='gstamt',
            field=models.DecimalField(blank=True, db_column='VendInv_GstAmt', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='method',
            field=models.CharField(db_column='VendInv_Method', default='direct', max_length=25),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='tdsamt',
            field=models.DecimalField(blank=True, db_column='VendInv_TdsAmt', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='apterm_days',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='apterm_key',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='cancelledby',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='cancelleddttm',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='contract_key',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='docid',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='docstatus',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='grn_key',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='itemtype_key',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='loctyp',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='submittedby',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='submitteddttm',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='vouchno',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='wh_key',
        ),
    ]
