# Generated by Django 4.0.5 on 2024-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('pricing', '0003_alter_vendorinvoice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('company', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderitems',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='desc',
            field=models.CharField(blank=True, db_column='PO_Desc', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='gstamt',
            field=models.DecimalField(blank=True, db_column='PO_GstAmt', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='netamt',
            field=models.DecimalField(blank=True, db_column='PO_NetAmt', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, db_column='PO_Status', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tdsamt',
            field=models.DecimalField(blank=True, db_column='PO_TdsAmt', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='brand',
            field=models.CharField(blank=True, db_column='POItm_Brand', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='model_number',
            field=models.CharField(blank=True, db_column='POItm_ModelNumber', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='unit',
            field=models.DecimalField(blank=True, db_column='POItm_Unit', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='cancelledby',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='cancelleddttm',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivnotes',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='docid',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='docstatus',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='itemtyp_key',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='loctyp',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purtmpl_key',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='submittedby',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='submitteddttm',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='wh_key',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='itemnotes',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='itemuom_key',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='qtyrecd',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='taxamt',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='totalamt',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='unitprice',
        ),
    ]
