# Generated by Django 4.0.5 on 2024-07-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0005_remove_contractagreementpaymentschedule_contract_agreement_id_and_more'),
        ('pricing', '0004_alter_purchaseorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='gstamt',
            field=models.DecimalField(db_column='PO_GstAmt', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='netamt',
            field=models.DecimalField(db_column='PO_NetAmt', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(db_column='PO_Status', default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tdsamt',
            field=models.DecimalField(db_column='PO_TdsAmt', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vend_key',
            field=models.ForeignKey(blank=True, db_column='PO_Vend_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
