# Generated by Django 4.0.5 on 2024-07-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_purchaseorder_gstamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='po_key',
            field=models.ForeignKey(blank=True, db_column='VendInv_PO_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.purchaseorder'),
        ),
    ]
