# Generated by Django 4.0.5 on 2024-07-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_vendorinvoice_po_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(db_column='PO_Status', default='O', max_length=2),
        ),
    ]
