# Generated by Django 4.0.5 on 2024-07-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docid',
        ),
    ]
