# Generated by Django 4.0.5 on 2024-07-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('pricing', '0008_delete_docid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docid',
            fields=[
                ('key', models.AutoField(db_column='DocKey', primary_key=True, serialize=False)),
                ('docid', models.CharField(db_column='DocID', max_length=5)),
                ('docname', models.CharField(db_column='DocName', max_length=50)),
                ('docnumber', models.IntegerField(db_column='DocNumber')),
                ('client_id', models.ForeignKey(db_column='DocID_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'DocID',
                'managed': True,
            },
        ),
    ]
