# Generated by Django 4.0.5 on 2024-10-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_vendorinvoice_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='invoice_status',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='paid_amount',
        ),
    ]
