# Generated by Django 4.0.5 on 2024-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_remove_vendorinvoice_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='invoice_status',
            field=models.CharField(choices=[('O', 'O'), ('P', 'P'), ('A', 'A')], db_column='VendorInv_InvoiceStatus', default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='paid_amount',
            field=models.DecimalField(blank=True, db_column='VendorInv_PaidAmount', decimal_places=2, max_digits=15, null=True),
        ),
    ]
