# Generated by Django 4.0.5 on 2024-11-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_vendorinvoice_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discountamt',
            field=models.DecimalField(db_column='PO_DiscountAmt', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='handling_chrgs',
            field=models.DecimalField(db_column='PO_HandlingChrgs', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rounded_action',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('S', 'S')], db_column='PO_RoundedAction', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='roundedamt',
            field=models.DecimalField(db_column='PO_RoundedAmt', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='transport_chrgs',
            field=models.DecimalField(db_column='PO_TransportChrgs', decimal_places=2, default=0, max_digits=15),
        ),
    ]
