# Generated by Django 4.0.5 on 2024-11-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_item_purpose_key'),
        ('pricing', '0013_purchaseorder_discountamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='item_uom_key',
            field=models.ForeignKey(blank=True, db_column='POItm_ItemUom_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom'),
        ),
    ]
