# Generated by Django 4.0.5 on 2025-02-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_purchaseorderitems_item_uom_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='vendor_invoice_no',
            field=models.CharField(db_column='VendInv_VendInvoiceNo', default='12345', max_length=100),
            preserve_default=False,
        ),
    ]
