# Generated by Django 4.0.5 on 2025-02-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_vendorinvoice_vendor_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='vendor_invoice_no',
            field=models.CharField(blank=True, db_column='VendInv_VendInvoiceNo', max_length=100, null=True),
        ),
    ]
