# Generated by Django 4.0.5 on 2025-04-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_alter_vendorinvoice_vendor_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='discountamt',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='handling_chrgs',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rounded_action',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='roundedamt',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='transport_chrgs',
        ),
    ]
