# Generated by Django 4.0.5 on 2025-04-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_remove_purchaseorder_discountamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='discountamt',
            field=models.DecimalField(db_column='VendInv_DiscountAmt', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='handling_chrgs',
            field=models.DecimalField(db_column='VendInv_HandlingChrgs', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='rounded_action',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('S', 'S')], db_column='VendInv_RoundedAction', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='roundedamt',
            field=models.DecimalField(db_column='VendInv_RoundedAmt', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='transport_chrgs',
            field=models.DecimalField(db_column='VendInv_TransportChrgs', decimal_places=2, default=0, max_digits=15),
        ),
    ]
