# Generated by Django 4.0.5 on 2025-04-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_vendorinvoice_discountamt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='gstamt',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tdsamt',
        ),
    ]
