# Generated by Django 4.0.5 on 2025-04-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0019_remove_purchaseorder_gstamt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='discountamt',
            field=models.DecimalField(blank=True, db_column='VendInv_DiscountAmt', decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='handling_chrgs',
            field=models.DecimalField(blank=True, db_column='VendInv_HandlingChrgs', decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='roundedamt',
            field=models.DecimalField(blank=True, db_column='VendInv_RoundedAmt', decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='transport_chrgs',
            field=models.DecimalField(blank=True, db_column='VendInv_TransportChrgs', decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
