# Generated by Django 4.0.5 on 2025-04-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_item_purpose_key'),
        ('pricing', '0020_alter_vendorinvoice_discountamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='item_type_key',
            field=models.ForeignKey(blank=True, db_column='PO_ItemType_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='netamt',
            field=models.DecimalField(blank=True, db_column='VendInv_NetAmt', decimal_places=2, max_digits=15, null=True),
        ),
    ]
