# Generated by Django 4.0.5 on 2025-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0021_purchaseorder_item_type_key_vendorinvoice_netamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='gst',
            field=models.DecimalField(blank=True, db_column='POItm_GSTPercent', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='gstamt',
            field=models.DecimalField(blank=True, db_column='POItm_GSTAmt', decimal_places=5, max_digits=15, null=True),
        ),
    ]
