# Generated by Django 4.0.5 on 2025-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0022_purchaseorderitems_gst_purchaseorderitems_gstamt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='roundedamt',
            field=models.DecimalField(blank=True, db_column='VendInv_RoundedAmt', decimal_places=3, default=0, max_digits=15, null=True),
        ),
    ]
