# Generated by Django 4.0.5 on 2025-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0023_alter_vendorinvoice_roundedamt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='gst',
            field=models.IntegerField(blank=True, db_column='POItm_GSTPercent', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='gstamt',
            field=models.DecimalField(blank=True, db_column='POItm_GSTAmt', decimal_places=2, max_digits=15, null=True),
        ),
    ]
