# Generated by Django 4.0.5 on 2025-05-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0024_alter_purchaseorderitems_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='brand',
        ),
    ]
