# Generated by Django 4.0.5 on 2025-05-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_brand'),
        ('pricing', '0025_remove_purchaseorderitems_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='brand',
            field=models.ForeignKey(blank=True, db_column='POItm_Brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand'),
        ),
    ]
