# Generated by Django 4.0.5 on 2025-12-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0026_purchaseorderitems_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvoiceImage',
            fields=[
                ('key', models.AutoField(db_column='VendInvImg_Key', primary_key=True, serialize=False)),
                ('image_url', models.TextField(db_column='VendInvImg_URL')),
                ('client_id', models.IntegerField(db_column='VendInvImg_Client_ID')),
                ('company_id', models.IntegerField(db_column='VendInvImg_Company_ID')),
                ('createdby', models.CharField(blank=True, db_column='VendInvImg_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='VendInvImg_CreatedDtTm')),
                ('lastmodifiedby', models.CharField(blank=True, db_column='VendInvImg_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='VendInvImg_LastModifiedDtTm', null=True)),
                ('vendor_invoice', models.ForeignKey(db_column='VendInvImg_Inv_Key', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_images', to='pricing.vendorinvoice')),
            ],
            options={
                'db_table': 'VendorInvoice_Images',
            },
        ),
    ]
