# Generated by Django 4.0.5 on 2026-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0027_vendorinvoiceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='invnotes',
            field=models.TextField(blank=True, db_column='VendInv_InvNotes', max_length=500, null=True),
        ),
    ]
