# Generated by Django 4.0.5 on 2024-06-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('key', models.AutoField(db_column='State_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='State_ID', max_length=30, unique=True)),
                ('name', models.CharField(db_column='State_Name', max_length=100)),
            ],
            options={
                'db_table': 'State',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('key', models.AutoField(db_column='City_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='City_Name', max_length=100)),
                ('createdby', models.CharField(blank=True, db_column='City_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='City_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='City_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='City_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='City_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='City_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('state_key', models.ForeignKey(db_column='City_State_Key', on_delete=django.db.models.deletion.CASCADE, to='geolocation.state')),
            ],
            options={
                'db_table': 'City',
                'managed': True,
                'unique_together': {('company', 'state_key', 'name')},
            },
        ),
    ]
