# Generated by Django 4.0.5 on 2025-04-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing', '0019_remove_purchaseorder_gstamt_and_more'),
        ('project', '0019_alter_paidexpenses_payment_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAndAllowance',
            fields=[
                ('key', models.AutoField(db_column='Salary&Allowance_Key', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Salary&Allowance_Date')),
                ('amount', models.DecimalField(db_column='Salary&Allowance__Amount', decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('S', 'Salary'), ('A', 'Allowance')], db_column='Salary&Allowance_Type', max_length=1)),
                ('transaction_detail', models.CharField(blank=True, db_column='Salary&Allowance_TransactionDetail', max_length=255, null=True)),
                ('notes', models.CharField(blank=True, db_column='Salary&Allowance_Notes', max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, db_column='Salary&Allowance_CreatedBy', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Salary&Allowance_CreatedAt', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='Salary&Allowance_UpdatedBy', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Salary&Allowance_UpdatedAt', null=True)),
                ('account_key', models.ForeignKey(blank=True, db_column='Salary&Allowance__AccountKey', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.bankaccount')),
                ('client_id', models.ForeignKey(blank=True, db_column='Salary&Allowance_ClientID', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(blank=True, db_column='Salary&Allowance_CompanyID', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('employee', models.ForeignKey(db_column='Salary&Allowance_EmpKey', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_mode_key', models.ForeignKey(blank=True, db_column='Salary&Allowance__ModeofPayKey', null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.modeofpay')),
                ('project_key', models.ForeignKey(blank=True, db_column='Salary&Allowance__ProjKey', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'SalaryAndAllowance',
                'managed': True,
            },
        ),
    ]
