# Generated by Django 4.0.5 on 2024-06-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('client', '0001_initial'),
        ('inventory', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendorcontract',
            fields=[
                ('key', models.AutoField(db_column='VendCtr_Key', primary_key=True, serialize=False)),
                ('docid', models.CharField(db_column='VendCtr_DocID', max_length=3)),
                ('contractno', models.CharField(db_column='VendCtr_ContractNo', max_length=25)),
                ('contractdate', models.DateField(db_column='VendCtr_ContractDate')),
                ('notes', models.CharField(blank=True, db_column='VendCtr_Notes', max_length=255, null=True)),
                ('docstatus', models.CharField(blank=True, db_column='VendCtr_DocStatus', max_length=2, null=True)),
                ('submitteddttm', models.DateTimeField(blank=True, db_column='VendCtr_SubmittedDtTm', null=True)),
                ('submittedby', models.CharField(blank=True, db_column='VendCtr_SubmittedBy', max_length=100, null=True)),
                ('cancelleddttm', models.DateTimeField(blank=True, db_column='VendCtr_CancelledDtTm', null=True)),
                ('cancelledby', models.CharField(blank=True, db_column='VendCtr_CancelledBy', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='VendCtr_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='VendCtr_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='VendCtr_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='VendCtr_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='VendCtr_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='VendCtr_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('proj_key', models.ForeignKey(db_column='VendCtr_Proj_Key', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('vend_key', models.ForeignKey(db_column='VendCtr_Vend_Key', on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'db_table': 'VendorContract',
                'managed': True,
                'unique_together': {('company', 'docid', 'contractno')},
            },
        ),
        migrations.CreateModel(
            name='VendorcontractTasks',
            fields=[
                ('key', models.AutoField(db_column='VendCtrTsk_Key', primary_key=True, serialize=False)),
                ('item_descr', models.CharField(blank=True, db_column='VendCtrTsk_Item_Descr', max_length=100, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='VendCtrTsk_Qty', decimal_places=5, max_digits=15, null=True)),
                ('unitprice', models.DecimalField(blank=True, db_column='VendCtrTsk_UnitPrice', decimal_places=2, max_digits=15, null=True)),
                ('netamt', models.DecimalField(blank=True, db_column='VendCtrTsk_NetAmt', decimal_places=2, max_digits=15, null=True)),
                ('itemnotes', models.CharField(blank=True, db_column='VendCtrTsk_ItemNotes', max_length=255, null=True)),
                ('createdby', models.CharField(blank=True, db_column='VendCtrTsk_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='VendCtrTsk_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='VendCtrTsk_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='VendCtrTsk_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='VendCtrTsk_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='VendCtrTsk_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('itemuom_key', models.ForeignKey(db_column='VendCtrTsk_ItemUOM_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom')),
                ('vendctr_key', models.ForeignKey(db_column='VendCtrTsk_VendCtr_Key', on_delete=django.db.models.deletion.CASCADE, to='contractor.vendorcontract')),
            ],
            options={
                'db_table': 'VendorContract_Tasks',
                'managed': True,
                'unique_together': {('company', 'vendctr_key', 'item_descr', 'itemuom_key')},
            },
        ),
        migrations.CreateModel(
            name='VendorcontractStages',
            fields=[
                ('key', models.AutoField(db_column='VendCtrStg_Key', primary_key=True, serialize=False)),
                ('item_descr', models.CharField(blank=True, db_column='VendCtrStg_Item_Descr', max_length=100, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='VendCtrStg_Qty', decimal_places=5, max_digits=15, null=True)),
                ('unitprice', models.DecimalField(blank=True, db_column='VendCtrStg_UnitPrice', decimal_places=2, max_digits=15, null=True)),
                ('netamt', models.DecimalField(blank=True, db_column='VendCtrStg_NetAmt', decimal_places=2, max_digits=15, null=True)),
                ('invoiced', models.CharField(blank=True, db_column='VendCtrStg_Invoiced', max_length=1, null=True)),
                ('itemnotes', models.CharField(blank=True, db_column='VendCtrStg_ItemNotes', max_length=255, null=True)),
                ('createdby', models.CharField(blank=True, db_column='VendCtrStg_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='VendCtrStg_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='VendCtrStg_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='VendCtrStg_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='VendCtrStg_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='VendCtrStg_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('itemuom_key', models.ForeignKey(db_column='VendCtrStg_ItemUOM_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom')),
                ('vendctr_key', models.ForeignKey(db_column='VendCtrStg_VendCtr_Key', on_delete=django.db.models.deletion.CASCADE, to='contractor.vendorcontract')),
            ],
            options={
                'db_table': 'VendorContract_Stages',
                'managed': True,
                'unique_together': {('company', 'vendctr_key', 'item_descr', 'itemuom_key')},
            },
        ),
    ]
