# Generated by Django 4.0.5 on 2024-06-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('project', '0001_initial'),
        ('client', '0001_initial'),
        ('vendor', '0005_remove_contractagreementpaymentschedule_contract_agreement_id_and_more'),
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('key', models.AutoField(db_column='ContractAgreementKey', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ContractAgreementID', max_length=30)),
                ('agreement_no', models.CharField(db_column='ContractAgreementNo', max_length=100, unique=True)),
                ('agreement_date', models.DateField(db_column='ContractAgreementDate')),
                ('total_amount', models.DecimalField(blank=True, db_column='ContractAgreementTotalAmount', decimal_places=2, max_digits=15, null=True)),
                ('paid_amount', models.DecimalField(blank=True, db_column='ContractAgreementPaidAmount', decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, db_column='ContractAgreementNotes', null=True)),
                ('client_id', models.ForeignKey(db_column='ContractAgreementClient_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='ContractAgreementCompany_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('contractor_id', models.ForeignKey(db_column='ContractAgreementContractorID', on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
                ('project_id', models.ForeignKey(db_column='ContractAgreementProjectID', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'ContractAgreement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContractAgreementPaymentSchedule',
            fields=[
                ('key', models.AutoField(db_column='CAPaymentScheduleKey', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='CAPaymentScheduleID', max_length=30)),
                ('payment_stage_desc', models.CharField(db_column='CAPaymentScheduleDesc', max_length=500)),
                ('amount', models.DecimalField(db_column='CAPaymentScheduleAmnt', decimal_places=2, max_digits=10)),
                ('contract_agreement_id', models.ForeignKey(db_column='CAPaymentScheduleAgreementID', on_delete=django.db.models.deletion.CASCADE, to='contractor.contractagreement')),
            ],
            options={
                'db_table': 'ContractAgreementPaymentSchedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContractorInvoice',
            fields=[
                ('key', models.AutoField(db_column='ContractorInvoiceKey', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ContractorInvoiceID', max_length=30)),
                ('invoice_id', models.CharField(db_column='ContractorInvoice_InvoiceID', max_length=100, unique=True)),
                ('invoice_date', models.DateField(db_column='ContractorInvoice_InvoiceDate')),
                ('invoice_amount', models.DecimalField(blank=True, db_column='ContractorInvoice_InvoiceAmount', decimal_places=2, max_digits=15, null=True)),
                ('tds_amount', models.DecimalField(blank=True, db_column='ContractorInvoice_TDSAmount', decimal_places=2, max_digits=15, null=True)),
                ('invoice_type', models.CharField(choices=[('C', 'C'), ('N', 'N')], db_column='ContractorInvoice_InvoiceType', max_length=1)),
                ('invoice_desc', models.CharField(db_column='ContractorInvoice_InvoiceDesc', max_length=500)),
                ('agreement_id', models.ForeignKey(blank=True, db_column='ContractorInvoice_AgreementID', null=True, on_delete=django.db.models.deletion.CASCADE, to='contractor.contractagreement')),
                ('client_id', models.ForeignKey(db_column='ContractorInvoice_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='ContractorInvoice_CompanyID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('payment_schedule_id', models.ForeignKey(db_column='ContractorInvoice_PaymentScheldueID', null=True, on_delete=django.db.models.deletion.CASCADE, to='contractor.contractagreementpaymentschedule')),
                ('project_id', models.ForeignKey(db_column='ContractorInvoice_ProjectID', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'ContractorInvoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContractAgreementService',
            fields=[
                ('key', models.AutoField(db_column='CAServiceKey', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='CAServiceID', max_length=30)),
                ('service_desc', models.CharField(db_column='CAServiceDesc', max_length=500)),
                ('quantity', models.IntegerField(db_column='CAServiceQuantity')),
                ('rate_per_unit', models.DecimalField(db_column='CAServiceRatePerUnit', decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(db_column='CAServiceCost', decimal_places=2, max_digits=10)),
                ('contract_agreement_id', models.ForeignKey(db_column='CAServiceAgreementID', on_delete=django.db.models.deletion.CASCADE, to='contractor.contractagreement')),
                ('uom', models.ForeignKey(db_column='CAServiceUOMID', on_delete=django.db.models.deletion.CASCADE, to='inventory.uomtype')),
            ],
            options={
                'db_table': 'ContractAgreementService',
                'managed': True,
            },
        ),
    ]
