# Generated by Django 4.0.5 on 2024-06-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_contractagreement_contractagreementpaymentschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractagreementpaymentschedule',
            name='id',
            field=models.CharField(db_column='CAPaymentScheduleID', max_length=255),
        ),
    ]
