# Generated by Django 4.0.5 on 2024-07-01 11:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('geolocation', '0001_initial'),
        ('contractor', '0003_alter_contractagreementpaymentschedule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorType',
            fields=[
                ('key', models.AutoField(db_column='ContractorTyp_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ContractorTyp_ID', max_length=30)),
                ('descr', models.CharField(blank=True, db_column='ContractorTyp_Descr', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='ContractorTyp_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='ContractorTyp_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ContractorTyp_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='ContractorTyp_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='ContractorTyp_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='ContractorTyp_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'db_table': 'ContractorType',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('key', models.AutoField(db_column='Contractor_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='Contractor_ID', max_length=30)),
                ('name', models.CharField(db_column='Contractor_Name', max_length=100)),
                ('addr1', models.CharField(blank=True, db_column='Contractor_Addr1', max_length=100, null=True)),
                ('addr2', models.CharField(blank=True, db_column='Contractor_Addr2', max_length=100, null=True)),
                ('pincode', models.IntegerField(db_column='Contractor_PinCode')),
                ('gstnumber', models.CharField(blank=True, db_column='Contractor_GSTNumber', max_length=20, null=True)),
                ('itemtype_keys', models.CharField(db_column='Contractor_ItemTyp_Keys', max_length=255)),
                ('phoneno', models.CharField(blank=True, db_column='Contractor_ContactPhoneNo', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^\\+?1?\\d{9,15}$')])),
                ('landline_no', models.CharField(blank=True, db_column='Contractor_ContactLandlineNo', max_length=255, null=True)),
                ('email_id', models.CharField(blank=True, db_column='Contractor_ContactEmailID', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^\\+?1?\\d{9,15}$')])),
                ('inactive', models.CharField(blank=True, db_column='Contractor_InActive', default='N', max_length=1, null=True)),
                ('inhouse', models.CharField(blank=True, db_column='Contractor_InHouse', default='N', max_length=1, null=True)),
                ('createdby', models.CharField(blank=True, db_column='Contractor_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='Contractor_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='Contractor_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='Contractor_LastModifiedDtTm', null=True)),
                ('city_key', models.ForeignKey(blank=True, db_column='Contractor_City_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.city')),
                ('client_id', models.ForeignKey(db_column='Contractor_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Contractor_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('contractortyp_key', models.ForeignKey(db_column='Contractor_ContractorTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='contractor.contractortype')),
                ('state_key', models.ForeignKey(blank=True, db_column='Contractor_State_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.state')),
            ],
            options={
                'db_table': 'Contractor',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
    ]
