# Generated by Django 4.0.5 on 2024-07-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('contractor', '0004_contractortype_contractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='company',
            new_name='company_id',
        ),
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together={('company_id', 'id')},
        ),
        migrations.AlterField(
            model_name='contractagreement',
            name='contractor_id',
            field=models.ForeignKey(db_column='ContractAgreementContractorID', on_delete=django.db.models.deletion.CASCADE, to='contractor.contractor'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email_id',
            field=models.CharField(blank=True, db_column='Contractor_ContactEmailID', max_length=255, null=True),
        ),
    ]
