# Generated by Django 4.0.5 on 2024-07-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('contractor', '0005_rename_company_contractor_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInvAllocAmt',
            fields=[
                ('key', models.AutoField(db_column='ContractInvAllocAmt_Key', primary_key=True, serialize=False)),
                ('allocated_amount', models.IntegerField(db_column='ContractInvAllocAmt_AllocatedAmount')),
                ('client_id', models.ForeignKey(db_column='ContractInvAllocAmt_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('invoice_id', models.ForeignKey(db_column='ContractInvAllocAmt_InvoiceID', on_delete=django.db.models.deletion.CASCADE, to='contractor.contractorinvoice')),
            ],
            options={
                'db_table': 'ContractInvAllocAmt',
            },
        ),
    ]
