# Generated by Django 4.0.5 on 2024-07-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('pricing', '0002_docid_client_id'),
        ('contractor', '0006_contractinvallocamt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractVoucherHdr',
            fields=[
                ('key', models.AutoField(db_column='ContractVoucherHdr_Key', primary_key=True, serialize=False)),
                ('voucher_number', models.IntegerField(db_column='ContractVoucherHdr_VoucherNumber')),
                ('contract_voucher_dttm', models.DateTimeField(db_column='ContractVoucherHdr_ContractVoucherDtTm')),
                ('transaction_detail', models.CharField(db_column='ContractVoucherHdr_TransactionDetail', max_length=255)),
                ('notes', models.CharField(db_column='ContractVoucherHdr_Notes', max_length=255)),
                ('total_amount', models.IntegerField(db_column='ContractVoucherHdr_TotalAmount')),
                ('account', models.ForeignKey(db_column='ContractVoucherHdr_AccountID', on_delete=django.db.models.deletion.CASCADE, to='client.bankaccount')),
                ('client_id', models.ForeignKey(db_column='ContractVoucherHdr_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='ContractVoucherHdr_CompanyID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('payment_mode', models.ForeignKey(db_column='ContractVoucherHdr_PaymentModeID', on_delete=django.db.models.deletion.CASCADE, to='pricing.modeofpay')),
            ],
            options={
                'db_table': 'ContractVoucherHdr',
            },
        ),
        migrations.CreateModel(
            name='ContractVoucherDtl',
            fields=[
                ('key', models.AutoField(db_column='ContractVoucherDtl_Key', primary_key=True, serialize=False)),
                ('paid_amount', models.IntegerField(db_column='ContractVoucherDtl_PaidAmount')),
                ('contract_voucher_hdr', models.ForeignKey(db_column='ContractVoucherDtl_ContractVoucherHdrKey', on_delete=django.db.models.deletion.CASCADE, to='contractor.contractvoucherhdr')),
                ('invoice_id', models.ForeignKey(db_column='ContractVoucherDtl_InvoiceID', on_delete=django.db.models.deletion.CASCADE, to='contractor.contractorinvoice')),
            ],
            options={
                'db_table': 'ContractVoucherDtl',
            },
        ),
    ]
