# Generated by Django 4.0.5 on 2024-07-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0007_contractvoucherhdr_contractvoucherdtl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractvoucherhdr',
            old_name='account',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='contractvoucherhdr',
            old_name='payment_mode',
            new_name='payment_mode_id',
        ),
    ]
