# Generated by Django 4.0.5 on 2024-07-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('contractor', '0008_rename_account_contractvoucherhdr_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorinvoice',
            name='paid_amount',
            field=models.DecimalField(blank=True, db_column='ContractorInvoice_PaidAmount', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='contractvoucherdtl',
            name='client_id',
            field=models.ForeignKey(db_column='ContractVoucherDtl_ClientID', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.clientbase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractvoucherhdr',
            name='contractor_id',
            field=models.ForeignKey(db_column='ContractVoucherHdr_ContractorID', default=1, on_delete=django.db.models.deletion.CASCADE, to='contractor.contractor'),
            preserve_default=False,
        ),
    ]
