# Generated by Django 4.0.5 on 2024-07-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0009_contractorinvoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='itemtype_keys',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='pincode',
            field=models.IntegerField(db_column='Contractor_PinCode', null=True),
        ),
    ]
