# Generated by Django 4.0.5 on 2024-07-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0010_remove_contractor_itemtype_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorinvoice',
            name='contractor_id',
            field=models.ForeignKey(blank=True, db_column='ContractorInvoice_ContractorID', default=1, on_delete=django.db.models.deletion.CASCADE, to='contractor.contractor'),
            preserve_default=False,
        ),
    ]
