# Generated by Django 4.0.5 on 2024-07-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0011_contractorinvoice_contractor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractvoucherhdr',
            name='contract_voucher_dttm',
        ),
        migrations.AddField(
            model_name='contractvoucherhdr',
            name='contract_voucher_dt',
            field=models.DateField(db_column='ContractVoucherHdr_ContractVoucherDate', default='2024-07-07'),
            preserve_default=False,
        ),
    ]
