# Generated by Django 4.0.5 on 2024-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0012_remove_contractvoucherhdr_contract_voucher_dttm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorinvoice',
            name='invoice_status',
            field=models.CharField(choices=[('O', 'O'), ('P', 'P'), ('A', 'A')], db_column='ContractorInvoice_InvoiceStatus', default='O', max_length=1),
        ),
    ]
