# Generated by Django 4.0.5 on 2024-07-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('contractor', '0013_contractorinvoice_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractagreementservice',
            name='uom',
            field=models.ForeignKey(db_column='CAServiceUOMID', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom'),
        ),
    ]
