# Generated by Django 4.0.5 on 2024-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0014_alter_contractagreementservice_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvoucherhdr',
            name='notes',
            field=models.CharField(db_column='ContractVoucherHdr_Notes', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractvoucherhdr',
            name='transaction_detail',
            field=models.CharField(db_column='ContractVoucherHdr_TransactionDetail', max_length=255, null=True),
        ),
    ]
