# Generated by Django 4.0.5 on 2024-10-14 10:45

from django.db import migrations


def convert_quantity_to_decimal(apps, schema_editor):
    ContractAgreementService = apps.get_model(
        'contractor', 'ContractAgreementService')

    # Convert quantity from Integer to Decimal
    for service in ContractAgreementService.objects.all():
        service.quantity = float(service.quantity)
        service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0015_alter_contractvoucherhdr_notes_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_quantity_to_decimal),
    ]
