# Generated by Django 4.0.5 on 2024-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0016_convert_quantity_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractagreementservice',
            name='quantity',
            field=models.DecimalField(db_column='CAServiceQuantity', decimal_places=2, max_digits=10),
        ),
    ]
