# Generated by Django 4.0.5 on 2024-10-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('contractor', '0017_alter_contractagreementservice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvoucherhdr',
            name='account_id',
            field=models.ForeignKey(blank=True, db_column='ContractVoucherHdr_AccountID', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.bankaccount'),
        ),
        migrations.AlterField(
            model_name='contractvoucherhdr',
            name='notes',
            field=models.CharField(blank=True, db_column='ContractVoucherHdr_Notes', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractvoucherhdr',
            name='transaction_detail',
            field=models.CharField(blank=True, db_column='ContractVoucherHdr_TransactionDetail', max_length=255, null=True),
        ),
    ]
