# Generated by Django 4.0.5 on 2024-10-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0018_alter_contractvoucherhdr_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorinvoice',
            name='id',
        ),
    ]
