# Generated by Django 4.0.5 on 2024-10-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0019_remove_contractorinvoice_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='id',
        ),
    ]
