# Generated by Django 4.0.5 on 2024-10-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0020_alter_contractor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractortype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contractortype',
            name='id',
        ),
    ]
