# Generated by Django 4.0.5 on 2024-10-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0021_alter_contractortype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorinvoice',
            name='invoice_desc',
            field=models.CharField(blank=True, db_column='ContractorInvoice_InvoiceDesc', max_length=500, null=True),
        ),
    ]
