# Generated by Django 4.0.5 on 2024-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0022_alter_contractorinvoice_invoice_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='pan_no',
            field=models.CharField(blank=True, db_column='Contractor_PanNo', max_length=10, null=True),
        ),
    ]
