# Generated by Django 4.0.5 on 2024-11-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0023_contractor_pan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorinvoice',
            name='payable_amount',
            field=models.DecimalField(blank=True, db_column='ContractorInvoice_PayableAmount', decimal_places=2, max_digits=15, null=True),
        ),
    ]
