# Generated by Django 4.0.5 on 2025-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0024_contractorinvoice_payable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractagreementpaymentschedule',
            name='stage_status',
            field=models.CharField(choices=[('O', 'O'), ('I', 'I')], db_column='CAPaymentScheduleStatus', default='O', max_length=1),
        ),
    ]
