# Generated by Django 4.0.5 on 2024-07-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractServiceTemplateHdr',
            fields=[
                ('key', models.AutoField(db_column='ContractServiceTemplateHdr_Key', primary_key=True, serialize=False)),
                ('template_name', models.CharField(db_column='ContractServiceTemplateHdr_TemplateName', max_length=255)),
                ('description', models.TextField(db_column='ContractServiceTemplateHdr_Description')),
                ('contract_type_key', models.CharField(db_column='ContractServiceTemplateHdr_ContractTypeKey', max_length=255)),
                ('clientid', models.IntegerField(db_column='ContractServiceTemplateHdr_ClientID')),
            ],
            options={
                'db_table': 'ContractServiceTemplateHdr',
            },
        ),
        migrations.CreateModel(
            name='ContractServiceTemplateDtl',
            fields=[
                ('key', models.AutoField(db_column='ContractServiceTemplateDtl_Key', primary_key=True, serialize=False)),
                ('service_desc', models.TextField(db_column='ContractServiceTemplateDtl_ServiceDesc')),
                ('clientid', models.IntegerField(db_column='ContractServiceTemplateDtl_ClientID')),
                ('contractservice_template_hdr_key', models.ForeignKey(db_column='ContractServiceTemplateDtl_ContractServiceTemplateHdrKey', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='templates.contractservicetemplatehdr')),
                ('uom', models.ForeignKey(db_column='ContractServiceTemplateDtl_UOM', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom')),
            ],
            options={
                'db_table': 'ContractServiceTemplateDtl',
            },
        ),
    ]
