# Generated by Django 4.0.5 on 2024-07-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentScheduleTemplateHdr',
            fields=[
                ('key', models.AutoField(db_column='PaymentScheduleTemplateHdr_Key', primary_key=True, serialize=False)),
                ('template_name', models.CharField(db_column='PaymentScheduleTemplateHdr_TemplateName', max_length=255)),
                ('description', models.TextField(db_column='PaymentScheduleTemplateHdr_Description')),
                ('contract_type_key', models.CharField(db_column='PaymentScheduleTemplateHdr_ContractTypeKey', max_length=255)),
                ('clientid', models.IntegerField(db_column='PaymentScheduleTemplateHdr_ClientID')),
            ],
            options={
                'db_table': 'PaymentScheduleTemplateHdr',
            },
        ),
        migrations.RenameField(
            model_name='contractservicetemplatedtl',
            old_name='clientid',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='contractservicetemplatehdr',
            old_name='clientid',
            new_name='client_id',
        ),
        migrations.CreateModel(
            name='PaymentScheduleTemplateDtl',
            fields=[
                ('key', models.AutoField(db_column='PaymentScheduleTemplateDtl_Key', primary_key=True, serialize=False)),
                ('service_desc', models.TextField(db_column='PaymentScheduleTemplateDtl_ServiceDesc')),
                ('clientid', models.IntegerField(db_column='PaymentScheduleTemplateDtl_ClientID')),
                ('payment_schedule_template_hdr_key', models.ForeignKey(db_column='PaymentScheduleTemplateDtl_PaymentScheduleTemplateHdrKey', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='templates.paymentscheduletemplatehdr')),
            ],
            options={
                'db_table': 'PaymentScheduleTemplateDtl',
            },
        ),
    ]
