# Generated by Django 4.0.5 on 2024-07-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_paymentscheduletemplatehdr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentscheduletemplatedtl',
            name='service_desc',
        ),
        migrations.AddField(
            model_name='paymentscheduletemplatedtl',
            name='schedule_desc',
            field=models.TextField(db_column='PaymentScheduleTemplateDtl_SchedlueDesc', default='desc'),
            preserve_default=False,
        ),
    ]
