# Generated by Django 4.0.5 on 2024-07-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_remove_paymentscheduletemplatedtl_service_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentscheduletemplatedtl',
            name='schedule_desc',
        ),
        migrations.AddField(
            model_name='paymentscheduletemplatedtl',
            name='payment_stage_desc',
            field=models.TextField(db_column='PaymentScheduleTemplateDtl_ScheduleDesc', default='desc'),
            preserve_default=False,
        ),
    ]
