# Generated by Django 4.0.5 on 2025-02-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_item_purpose_key'),
        ('templates', '0004_remove_paymentscheduletemplatedtl_schedule_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemKitTemplateHdr',
            fields=[
                ('key', models.AutoField(db_column='ItemKitTemplateHdr_Key', primary_key=True, serialize=False)),
                ('kit_name', models.CharField(db_column='ItemKitTemplateHdr_Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='ItemKitTemplateHdr_Descr', null=True)),
                ('client_id', models.IntegerField(db_column='ItemKitTemplateHdr_ClientID')),
                ('item_type_key', models.ForeignKey(db_column='ItemKitTemplateHdr_ContractTypeKey', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
                ('purpose_key', models.ForeignKey(db_column='ItemKitTemplateHdr_PurposeKey', on_delete=django.db.models.deletion.CASCADE, to='inventory.purpose')),
            ],
            options={
                'db_table': 'ItemKitTemplateHdr',
            },
        ),
        migrations.CreateModel(
            name='ItemKitTemplateDtl',
            fields=[
                ('key', models.AutoField(db_column='ItemKitTemplateDtl_Key', primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, db_column='ItemKitTemplateDtl_Brand', max_length=255, null=True)),
                ('model', models.CharField(blank=True, db_column='ItemKitTemplateDtl_Model', max_length=255, null=True)),
                ('quantity', models.DecimalField(blank=True, db_column='ItemKitTemplateDtl_Quantity', decimal_places=2, max_digits=15, null=True)),
                ('client_id', models.IntegerField(db_column='ItemKitTemplateDtl_ClientID')),
                ('item_key', models.ForeignKey(db_column='ItemKitTemplateDtl_ItemKey', on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('item_kit_template_hdr_key', models.ForeignKey(db_column='ItemKitTemplateDtl_ItemKitTemplateHdrKey', on_delete=django.db.models.deletion.CASCADE, related_name='item_kit_hdr', to='templates.itemkittemplatehdr')),
                ('uom', models.ForeignKey(db_column='ItemKitTemplateDtl_UOM', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom')),
            ],
            options={
                'db_table': 'ItemKitTemplateDtl',
            },
        ),
    ]
