# Generated by Django 4.0.5 on 2025-02-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_itemkittemplatehdr_itemkittemplatedtl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemkittemplatedtl',
            old_name='uom',
            new_name='item_uom_key',
        ),
        migrations.RenameField(
            model_name='itemkittemplatedtl',
            old_name='model',
            new_name='model_number',
        ),
        migrations.RenameField(
            model_name='itemkittemplatedtl',
            old_name='quantity',
            new_name='qty',
        ),
    ]
