# Generated by Django 4.0.5 on 2025-03-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_rename_uom_itemkittemplatedtl_item_uom_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemkittemplatehdr',
            name='item_type_key',
        ),
    ]
