# Generated by Django 4.0.5 on 2025-03-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_item_purpose_key'),
        ('templates', '0007_remove_itemkittemplatehdr_item_type_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemkittemplatehdr',
            name='item_type_key',
            field=models.ForeignKey(db_column='ItemKitTemplateHdr_ItemTypeKey', default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype'),
            preserve_default=False,
        ),
    ]
