# Generated by Django 4.0.5 on 2025-03-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_itemkittemplatehdr_item_type_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentScheduleTemplateHdr',
            fields=[
                ('key', models.AutoField(db_column='Customer_PymntSchdleTemplateHdr_Key', primary_key=True, serialize=False)),
                ('template_name', models.CharField(db_column='Customer_PymntSchdleTemplateHdr_TemplateName', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Customer_PymntSchdleTemplateHdr_Descr', null=True)),
                ('clientid', models.IntegerField(db_column='Customer_PymntSchdleTemplateHdr_ClientID')),
            ],
            options={
                'db_table': 'Customer_PymntSchdleTemplateHdr',
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentScheduleTemplateDtl',
            fields=[
                ('key', models.AutoField(db_column='Customer_PymntSchdleTemplateDtl_Key', primary_key=True, serialize=False)),
                ('payment_stage_desc', models.TextField(db_column='Customer_PymntSchdleTemplateDtl_ScheduleDesc')),
                ('clientid', models.IntegerField(db_column='Customer_PymntSchdleTemplateDtl_ClientID')),
                ('payment_schedule_template_hdr_key', models.ForeignKey(db_column='Customer_PymntSchdleTemplateDtl_TmplteHdrKey', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='templates.customerpaymentscheduletemplatehdr')),
            ],
            options={
                'db_table': 'Customer_PymntSchdleTemplateDtl',
            },
        ),
    ]
