# Generated by Django 4.0.5 on 2024-06-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocation', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('key', models.AutoField(db_column='Item_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='Item_ID', max_length=100)),
                ('descr', models.CharField(blank=True, db_column='Item_Descr', max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, db_column='Item_Model_Number', max_length=30, null=True)),
                ('stocktype', models.CharField(db_column='Item_StockType', max_length=1)),
                ('gst', models.IntegerField(db_column='Item_Gst')),
                ('amount', models.DecimalField(blank=True, db_column='Item_Amount', decimal_places=2, max_digits=15, null=True)),
                ('createdby', models.CharField(blank=True, db_column='Item_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='Item_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='Item_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='Item_LastModifiedDtTm', null=True)),
                ('itemuoms', models.CharField(blank=True, db_column='Item_ItemUOMs', max_length=5000, null=True)),
                ('client_id', models.ForeignKey(db_column='Item_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Item_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'db_table': 'Item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemtype',
            fields=[
                ('key', models.AutoField(db_column='ItemTyp_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ItemTyp_ID', max_length=30)),
                ('descr', models.CharField(blank=True, db_column='ItemTyp_Descr', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='ItemTyp_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='ItemTyp_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemTyp_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='ItemTyp_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='ItemTyp_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='ItemTyp_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'db_table': 'ItemType',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Uomtype',
            fields=[
                ('key', models.AutoField(db_column='UOMTyp_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='UOMTyp_ID', max_length=30)),
                ('descr', models.CharField(blank=True, db_column='UOMTyp_Descr', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='UOMTyp_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='UOMTyp_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='UOMTyp_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='UOMTyp_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='UOMTyp_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='UOMTyp_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'db_table': 'UOMType',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('key', models.AutoField(db_column='Mfr_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='Mfr_ID', max_length=30)),
                ('name', models.CharField(blank=True, db_column='Mfr_Name', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='Mfr_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='Mfr_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='Mfr_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='Mfr_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='Mfr_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Mfr_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('itemtyp_key', models.ForeignKey(db_column='Mfr_ItemTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
            ],
            options={
                'db_table': 'Manufacturer',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Itemuom',
            fields=[
                ('key', models.AutoField(db_column='ItemUOM_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ItemUOM_ID', max_length=30)),
                ('descr', models.CharField(blank=True, db_column='ItemUOM_Descr', max_length=100, null=True)),
                ('stockuom_key', models.IntegerField(blank=True, db_column='itemUOM_StockUOM_Key', null=True)),
                ('convunits', models.DecimalField(blank=True, db_column='ItemUOK_ConvUnits', decimal_places=5, max_digits=15, null=True)),
                ('createdby', models.CharField(blank=True, db_column='ItemUOM_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='ItemUOM_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemUOM_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='ItemUOM_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='ItemUOM_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='ItemUOM_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('itemtyp_key', models.ForeignKey(db_column='ItemUOM_ItemTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
                ('uomtyp_key', models.ForeignKey(blank=True, db_column='ItemUOM_UOMTyp_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.uomtype')),
            ],
            options={
                'db_table': 'ItemUOM',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Itemsubtype',
            fields=[
                ('key', models.AutoField(db_column='ItemSubTyp_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, db_column='ItemSubTyp_ID', max_length=30, null=True)),
                ('descr', models.CharField(blank=True, db_column='ItemSubTyp_Descr', max_length=100, null=True)),
                ('gst', models.IntegerField(db_column='ItemSubTyp_Gst')),
                ('spec_param', models.CharField(blank=True, db_column='ItemSubTyp_Spec_Param', max_length=5000, null=True)),
                ('uom_keys', models.CharField(blank=True, db_column='ItemSubTyp_Uom_Keys', max_length=1000, null=True)),
                ('createdby', models.CharField(blank=True, db_column='ItemSubTyp_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='ItemSubTyp_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemSubTyp_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='ItemSubTyp_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(blank=True, db_column='ItemSubTyp_Client_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(blank=True, db_column='ItemSubTyp_Company_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('itemtyp_key', models.ForeignKey(db_column='ItemSubTyp_ItemTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
            ],
            options={
                'db_table': 'ItemSubType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('key', models.AutoField(db_column='ItemSpec_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ItemSpec_ID', max_length=30)),
                ('name', models.CharField(blank=True, db_column='ItemSpec_Name', max_length=100, null=True)),
                ('value', models.CharField(blank=True, db_column='ItemSpec_Value', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='ItemSpec_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='ItemSpec_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemSpec_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='ItemSpec_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='ItemSpec_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='ItemSpec_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('item_key', models.ForeignKey(db_column='ItemSpec_Item_key', on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'db_table': 'ItemSpecification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemgroup',
            fields=[
                ('key', models.AutoField(db_column='ItemGrp_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ItemGrp_ID', max_length=30)),
                ('descr', models.CharField(blank=True, db_column='ItemGrp_Descr', max_length=100, null=True)),
                ('grouptype', models.CharField(db_column='ItemGrp_GroupType', max_length=1)),
                ('mixtype', models.CharField(db_column='ItemGrp_MixType', max_length=1)),
                ('scope', models.CharField(db_column='ItemGrp_Scope', max_length=1)),
                ('createdby', models.CharField(blank=True, db_column='ItemGrp_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='ItemGrp_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemGrp_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='ItemGrp_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='ItemGrp_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='ItemGrp_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('itemuom_key', models.ForeignKey(db_column='ItemGrp_ItemUOM_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom')),
            ],
            options={
                'db_table': 'ItemGroup',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='itemtyp_key',
            field=models.ForeignKey(db_column='Item_ItemTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemuom_key',
            field=models.ForeignKey(blank=True, db_column='Item_ItemUOM_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom'),
        ),
        migrations.AddField(
            model_name='item',
            name='mfr_key',
            field=models.ForeignKey(blank=True, db_column='Item_Mfr_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.manufacturer'),
        ),
        migrations.AddField(
            model_name='item',
            name='subtype',
            field=models.ForeignKey(blank=True, db_column='Item_SubType_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemsubtype'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('key', models.AutoField(db_column='WH_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='WH_ID', max_length=30)),
                ('name', models.CharField(db_column='WH_Name', max_length=100)),
                ('addr1', models.CharField(blank=True, db_column='WH_Addr1', max_length=100, null=True)),
                ('addr2', models.CharField(blank=True, db_column='WH_Addr2', max_length=100, null=True)),
                ('briefdescr', models.CharField(blank=True, db_column='WH_BriefDescr', max_length=255, null=True)),
                ('createdby', models.CharField(blank=True, db_column='WH_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='WH_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='WH_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='WH_LastModifiedDtTm', null=True)),
                ('city_key', models.ForeignKey(db_column='WH_City_Key', on_delete=django.db.models.deletion.CASCADE, to='geolocation.city')),
                ('client_id', models.ForeignKey(db_column='WH_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='WH_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('state_key', models.ForeignKey(db_column='WH_State_Key', on_delete=django.db.models.deletion.CASCADE, to='geolocation.state')),
            ],
            options={
                'db_table': 'Warehouse',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Itemgroupdetail',
            fields=[
                ('key', models.AutoField(db_column='ItemGrpDet_Key', primary_key=True, serialize=False)),
                ('mixratioval', models.DecimalField(blank=True, db_column='ItemGrpDet_MixRatioVal', decimal_places=3, max_digits=10, null=True)),
                ('createdby', models.CharField(blank=True, db_column='ItemGrpDet_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='ItemGrpDet_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemGrpDet_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='ItemGrpDet_LastModifiedDtTm', null=True)),
                ('company_id', models.CharField(db_column='ItemGrpDet_Company_ID', max_length=10)),
                ('client_id', models.ForeignKey(db_column='ItemGrpDet_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('item_key', models.ForeignKey(db_column='ItemGrpDet_Item_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('itemgrp_key', models.ForeignKey(db_column='ItemGrpDet_ItemGrp_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemgroup')),
            ],
            options={
                'db_table': 'ItemGroupDetail',
                'managed': True,
                'unique_together': {('company_id', 'itemgrp_key', 'item_key')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('company', 'id')},
        ),
    ]
