# Generated by Django 4.0.5 on 2024-08-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemgroupdetail',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemtype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemuom',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='uomtype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='itemsubtype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
        migrations.RemoveField(
            model_name='itemgroup',
            name='company',
        ),
        migrations.RemoveField(
            model_name='itemgroupdetail',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='itemtype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='itemuom',
            name='company',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='uomtype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='company',
        ),
    ]
