# Generated by Django 4.0.5 on 2024-08-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('inventory', '0002_alter_item_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpecificationValue',
            fields=[
                ('key', models.AutoField(db_column='ItemSpecVal_Key', primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, db_column='ItemSpecVal_Value', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='ItemSpecVal_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='ItemSpecVal_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemSpecVal_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='ItemSpecVal_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='ItemSpecVal_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('item_key', models.ForeignKey(db_column='ItemSpecVal_Item_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('item_spec_key', models.ForeignKey(db_column='ItemSpecVal_Spec_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemspecification')),
            ],
            options={
                'db_table': 'ItemSpecificationValue',
                'managed': True,
            },
        ),
    ]
