# Generated by Django 4.0.5 on 2024-08-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemspecificationvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='id',
        ),
    ]
