# Generated by Django 4.0.5 on 2024-08-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_itemtype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mfr_key',
        ),
    ]
