# Generated by Django 4.0.5 on 2024-08-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('inventory', '0006_delete_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('key', models.AutoField(db_column='Purpose_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Purpose_Name', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='Purpose_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='Purpose_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='Purpose_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='Purpose_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='Purpose_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('itemtyp_key', models.ForeignKey(db_column='Purpose_ItemTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
            ],
            options={
                'db_table': 'Purpose',
                'managed': True,
            },
        ),
    ]
