# Generated by Django 4.0.5 on 2024-08-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purpose_key',
            field=models.ForeignKey(blank=True, db_column='Item_Purpose_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purpose'),
        ),
    ]
