# Generated by Django 4.0.5 on 2024-08-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_purpose_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemuom',
            name='id',
        ),
    ]
