# Generated by Django 4.0.5 on 2024-08-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_itemuom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsubtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemsubtype',
            name='spec_param',
        ),
        migrations.RemoveField(
            model_name='itemsubtype',
            name='uom_keys',
        ),
        migrations.DeleteModel(
            name='ItemSpecificationValue',
        ),
    ]
