# Generated by Django 4.0.5 on 2024-08-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('inventory', '0010_remove_itemsubtype_id_remove_itemsubtype_spec_param_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSubtypeSpecification',
            fields=[
                ('key', models.AutoField(db_column='ItemSubtypeSpec_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(blank=True, db_column='ItemSubtypeSpec_Descr', max_length=255, null=True)),
                ('createdby', models.CharField(blank=True, db_column='ItemSubtypeSpec_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='ItemSubtypeSpec_CreatedDtTm')),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemSubtypeSpec_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='ItemSubtypeSpec_LastModifiedDtTm')),
                ('client_id', models.ForeignKey(db_column='ItemSubtypeSpec_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('item_subtype_key', models.ForeignKey(db_column='ItemSubtypeSpec_ItemSubtype_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemsubtype')),
            ],
            options={
                'db_table': 'ItemSubtypeSpecification',
                'managed': True,
            },
        ),
    ]
