# Generated by Django 4.0.5 on 2024-08-16 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_itemsubtypespecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemspecification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='name',
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='item_subtype_spec_key',
            field=models.ForeignKey(blank=True, db_column='ItemSpec_ItemSubtypeSpec_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemsubtypespecification'),
        ),
    ]
