# Generated by Django 4.0.5 on 2024-08-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('inventory', '0012_remove_itemspecification_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemItemUOM',
            fields=[
                ('key', models.AutoField(db_column='ItemItemUOM_Key', primary_key=True, serialize=False)),
                ('createdby', models.CharField(blank=True, db_column='ItemItemUOM_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='ItemItemUOM_CreatedDtTm')),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemItemUOM_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='ItemItemUOM_LastModifiedDtTm')),
                ('client_id', models.ForeignKey(db_column='ItemItemUOM_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('item_key', models.ForeignKey(db_column='ItemItemUOM_Item_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('item_uom_key', models.ForeignKey(db_column='ItemItemUOM_ItemUOM_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom')),
            ],
            options={
                'db_table': 'Item_ItemUOM',
                'managed': True,
            },
        ),
    ]
