# Generated by Django 4.0.5 on 2024-08-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('inventory', '0013_itemitemuom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSubtypeItemUOM',
            fields=[
                ('key', models.AutoField(db_column='ItemSubtypeUOM_Key', primary_key=True, serialize=False)),
                ('createdby', models.CharField(blank=True, db_column='ItemSubtypeUOM_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='ItemSubtypeUOM_CreatedDtTm')),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ItemSubtypeUOM_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='ItemSubtypeUOM_LastModifiedDtTm')),
                ('client_id', models.ForeignKey(db_column='ItemSubtypeUOM_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('item_subtype_key', models.ForeignKey(db_column='ItemSubtypeUOM_ItemSubtype_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemsubtype')),
                ('item_uom_key', models.ForeignKey(db_column='ItemSubtypeUOM_ItemUOM_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom')),
            ],
            options={
                'db_table': 'ItemSubtype_ItemUOM',
                'managed': True,
            },
        ),
    ]
