# Generated by Django 4.0.5 on 2024-08-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_itemsubtypeitemuom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsubtypeitemuom',
            name='createddttm',
            field=models.DateTimeField(blank=True, db_column='ItemSubtypeUOM_CreatedDtTm', null=True),
        ),
        migrations.AlterField(
            model_name='itemsubtypeitemuom',
            name='lastmodifieddttm',
            field=models.DateTimeField(blank=True, db_column='ItemSubtypeUOM_LastModifiedDtTm', null=True),
        ),
        migrations.AlterField(
            model_name='itemsubtypespecification',
            name='createddttm',
            field=models.DateTimeField(blank=True, db_column='ItemSubtypeSpec_CreatedDtTm', null=True),
        ),
        migrations.AlterField(
            model_name='itemsubtypespecification',
            name='lastmodifieddttm',
            field=models.DateTimeField(blank=True, db_column='ItemSubtypeSpec_LastModifiedDtTm', null=True),
        ),
    ]
