# Generated by Django 4.0.5 on 2024-08-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_itemsubtypeitemuom_createddttm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemuom_key',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemuoms',
        ),
    ]
