# Generated by Django 4.0.5 on 2024-08-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_item_id_remove_item_itemuom_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemitemuom',
            name='createddttm',
            field=models.DateTimeField(blank=True, db_column='ItemItemUOM_CreatedDtTm', null=True),
        ),
        migrations.AlterField(
            model_name='itemitemuom',
            name='lastmodifieddttm',
            field=models.DateTimeField(blank=True, db_column='ItemItemUOM_LastModifiedDtTm', null=True),
        ),
    ]
