# Generated by Django 4.0.5 on 2024-09-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('inventory', '0017_alter_itemitemuom_createddttm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPurpose',
            fields=[
                ('key', models.AutoField(db_column='ItemPurpose_Key', primary_key=True, serialize=False)),
                ('client_id', models.ForeignKey(db_column='ItemPurpose_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('item_key', models.ForeignKey(db_column='ItemPurpose_ItemKey', on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('purpose_key', models.ForeignKey(db_column='ItemPurpose_PurposeKey', on_delete=django.db.models.deletion.CASCADE, to='inventory.purpose')),
            ],
            options={
                'db_table': 'ItemPurpose',
                'managed': True,
            },
        ),
    ]
