# Generated by Django 4.0.5 on 2024-10-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_itempurpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purpose_key',
        ),
    ]
