# Generated by Django 4.0.5 on 2025-05-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('inventory', '0019_remove_item_purpose_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('key', models.AutoField(db_column='Brand_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Brand_Name', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='Brand_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='Brand_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='Brand_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='Brand_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='Brand_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('itemtyp_key', models.ForeignKey(db_column='Brand_ItemTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
            ],
            options={
                'db_table': 'Brand',
                'managed': True,
            },
        ),
    ]
