# Generated by Django 4.0.5 on 2024-10-25 12:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0017_alter_vendorpaymentvoucherdtl_paid_amount_and_more'),
        ('client', '0002_bankaccount'),
        ('contractor', '0022_alter_contractorinvoice_invoice_desc'),
        ('pricing', '0012_vendorinvoice_invoice_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TdsReport',
            fields=[
                ('key', models.AutoField(db_column='TDS_Report_Key', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='TDS_Report_Date')),
                ('entity_type', models.CharField(choices=[('V', 'Vendor'), ('C', 'Contractor')], db_column='TDS_Report_EntityType', max_length=1)),
                ('amount', models.DecimalField(db_column='TDS_Report_Amount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='TDS_Report_CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='TDS_Report_UpdatedAt')),
                ('client', models.ForeignKey(db_column='TDS_Report_ClientID', on_delete=django.db.models.deletion.CASCADE, related_name='tds_reports', to='client.clientbase')),
                ('company', models.ForeignKey(db_column='TDS_Report_CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='tds_reports', to='client.company')),
                ('contractor', models.ForeignKey(blank=True, db_column='TDS_Report_ContractorKey', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_reports', to='contractor.contractor')),
                ('vendor', models.ForeignKey(blank=True, db_column='TDS_Report_VendKey', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_reports', to='vendor.vendor')),
            ],
            options={
                'db_table': 'TdsReport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TdsEntry',
            fields=[
                ('key', models.AutoField(db_column='TDS_Entry_Key', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='TDS_Entry_Date')),
                ('invoice_type', models.CharField(choices=[('C', 'Contractor'), ('V', 'Vendor')], db_column='TDS_Entry_InvoiceType', max_length=1)),
                ('amount', models.DecimalField(db_column='TDS_Entry_Amount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], db_column='TDS_Entry_PaymentStatus', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='TDS_Entry_CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='TDS_Entry_UpdatedAt')),
                ('client', models.ForeignKey(db_column='TDS_Entry_ClientID', on_delete=django.db.models.deletion.CASCADE, related_name='tds_entries', to='client.clientbase')),
                ('company', models.ForeignKey(db_column='TDS_Entry_CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='tds_entries', to='client.company')),
                ('contractor_invoice', models.ForeignKey(blank=True, db_column='TDS_Entry_ContractorInvoiceID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_entries', to='contractor.contractorinvoice')),
                ('vendor_invoice', models.ForeignKey(blank=True, db_column='TDS_Entry_VendorInvoiceID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_entries', to='pricing.vendorinvoice')),
            ],
            options={
                'db_table': 'TdsEntries',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='tdsreport',
            index=models.Index(fields=['client'], name='TdsReport_TDS_Rep_250410_idx'),
        ),
        migrations.AddIndex(
            model_name='tdsreport',
            index=models.Index(fields=['company'], name='TdsReport_TDS_Rep_14b421_idx'),
        ),
        migrations.AddIndex(
            model_name='tdsentry',
            index=models.Index(fields=['date'], name='TdsEntries_TDS_Ent_e8b8b3_idx'),
        ),
        migrations.AddIndex(
            model_name='tdsentry',
            index=models.Index(fields=['payment_status'], name='TdsEntries_TDS_Ent_5cc0ec_idx'),
        ),
        migrations.AddIndex(
            model_name='tdsentry',
            index=models.Index(fields=['client'], name='TdsEntries_TDS_Ent_d19752_idx'),
        ),
        migrations.AddIndex(
            model_name='tdsentry',
            index=models.Index(fields=['company'], name='TdsEntries_TDS_Ent_650775_idx'),
        ),
    ]
