# Generated by Django 4.0.5 on 2024-10-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsreport',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], db_column='TDS_Report_PaymentStatus', default='Unpaid', max_length=6),
            preserve_default=False,
        ),
    ]
