# Generated by Django 4.0.5 on 2024-11-07 09:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0018_vendor_pan_no'),
        ('pricing', '0012_vendorinvoice_invoice_status_and_more'),
        ('client', '0002_bankaccount'),
        ('tax', '0002_tdsreport_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseGstReport',
            fields=[
                ('key', models.AutoField(db_column='Purch_GST_Report_Key', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Purch_GST_Report_Date')),
                ('gst_no', models.CharField(db_column='Purch_GST_Report_GSTNo', max_length=15)),
                ('gst_amount', models.DecimalField(db_column='Purch_GST_Report_Amount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Purch_GST_Report_CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Purch_GST_Report_UpdatedAt')),
                ('client', models.ForeignKey(db_column='Purch_GST_Report_ClientID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_gst_reports', to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Purch_GST_Report_CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_gst_reports', to='client.company')),
                ('vendor', models.ForeignKey(db_column='Purch_GST_Report_VendKey', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_gst_reports', to='vendor.vendor')),
            ],
            options={
                'db_table': 'PurchaseGSTReport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurchaseGstEntry',
            fields=[
                ('key', models.AutoField(db_column='Purch_GST_Entry_Key', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Purch_GST_Entry_Date')),
                ('gst_amount', models.DecimalField(db_column='Purch_GST_Entry_Amount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Purch_GST_Entry_CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Purch_GST_Entry_UpdatedAt')),
                ('client', models.ForeignKey(db_column='Purch_GST_Entry_ClientID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_gst_entries', to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Purch_GST_Entry_CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_gst_entries', to='client.company')),
                ('invoice', models.ForeignKey(db_column='Purch_GST_Entry_InvoiceID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_gst_entries', to='pricing.vendorinvoice')),
                ('vendor', models.ForeignKey(db_column='Purch_GST_Entry_VendKey', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_gst_entries', to='vendor.vendor')),
            ],
            options={
                'db_table': 'PurchaseGSTEntry',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='purchasegstreport',
            index=models.Index(fields=['date'], name='PurchaseGST_Purch_G_44cc76_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasegstreport',
            index=models.Index(fields=['gst_no'], name='PurchaseGST_Purch_G_58bbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasegstreport',
            index=models.Index(fields=['client'], name='PurchaseGST_Purch_G_03efe6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasegstreport',
            index=models.Index(fields=['company'], name='PurchaseGST_Purch_G_17bc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasegstentry',
            index=models.Index(fields=['date'], name='PurchaseGST_Purch_G_7c436a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasegstentry',
            index=models.Index(fields=['client'], name='PurchaseGST_Purch_G_0f6994_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasegstentry',
            index=models.Index(fields=['company'], name='PurchaseGST_Purch_G_b57a2d_idx'),
        ),
    ]
