# Generated by Django 4.0.5 on 2024-11-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_purchasegstreport_purchasegstentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasegstreport',
            name='gst_no',
            field=models.CharField(blank=True, db_column='Purch_GST_Report_GSTNo', max_length=15, null=True),
        ),
    ]
