# Generated by Django 4.0.5 on 2024-11-14 07:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('sale', '0009_sourceoffund_remove_saleinvoice_receivable_amount_and_more'),
        ('project', '0010_alter_paidexpenses_notes_and_more'),
        ('tax', '0004_alter_purchasegstreport_gst_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGstReport',
            fields=[
                ('key', models.AutoField(db_column='Sales_GST_Report_Key', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Sales_GST_Report_Date')),
                ('gst_amount', models.DecimalField(db_column='Sales_GST_Report_Amount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Sales_GST_Report_CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Sales_GST_Report_UpdatedAt')),
                ('agreement', models.ForeignKey(db_column='Sales_GST_Entry_AgreementID', on_delete=django.db.models.deletion.CASCADE, related_name='sale_gst_entries', to='sale.saleagreement')),
                ('client', models.ForeignKey(db_column='Sales_GST_Report_ClientID', on_delete=django.db.models.deletion.CASCADE, related_name='sales_gst_reports', to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Sales_GST_Report_CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='sales_gst_reports', to='client.company')),
                ('customer', models.ForeignKey(db_column='Sales_GST_Report_CustKey', on_delete=django.db.models.deletion.CASCADE, related_name='sales_gst_reports', to='sale.customer')),
                ('project', models.ForeignKey(db_column='Sales_GST_Report_ProjectID', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('unit', models.ForeignKey(db_column='Sales_GST_Report_UnitID', on_delete=django.db.models.deletion.CASCADE, to='project.projectunit')),
            ],
            options={
                'db_table': 'SalesGSTReport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesGstEntry',
            fields=[
                ('key', models.AutoField(db_column='Sales_GST_Entry_Key', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Sales_GST_Entry_Date')),
                ('gst_amount', models.DecimalField(db_column='Sales_GST_Entry_Amount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Sales_GST_Entry_CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Sales_GST_Entry_UpdatedAt')),
                ('client', models.ForeignKey(db_column='Sales_GST_Entry_ClientID', on_delete=django.db.models.deletion.CASCADE, related_name='sales_gst_entries', to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Sales_GST_Entry_CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='sales_gst_entries', to='client.company')),
                ('customer', models.ForeignKey(db_column='Sales_GST_Entry_CustKey', on_delete=django.db.models.deletion.CASCADE, related_name='sales_gst_entries', to='sale.customer')),
                ('invoice', models.ForeignKey(db_column='Sales_GST_Entry_InvoiceID', on_delete=django.db.models.deletion.CASCADE, related_name='sale_gst_entries', to='sale.saleinvoice')),
                ('project', models.ForeignKey(db_column='Sales_GST_Entry_ProjectID', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('unit', models.ForeignKey(db_column='Sales_GST_Entry_UnitID', on_delete=django.db.models.deletion.CASCADE, to='project.projectunit')),
            ],
            options={
                'db_table': 'SalesGSTEntry',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='salesgstreport',
            index=models.Index(fields=['date'], name='SalesGSTRep_Sales_G_e078d3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesgstreport',
            index=models.Index(fields=['client'], name='SalesGSTRep_Sales_G_068f50_idx'),
        ),
        migrations.AddIndex(
            model_name='salesgstreport',
            index=models.Index(fields=['company'], name='SalesGSTRep_Sales_G_3bd99b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesgstentry',
            index=models.Index(fields=['date'], name='SalesGSTEnt_Sales_G_c7ebc1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesgstentry',
            index=models.Index(fields=['client'], name='SalesGSTEnt_Sales_G_7c52df_idx'),
        ),
        migrations.AddIndex(
            model_name='salesgstentry',
            index=models.Index(fields=['company'], name='SalesGSTEnt_Sales_G_0d9a60_idx'),
        ),
    ]
