# Generated by Django 4.0.5 on 2024-11-20 16:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_remove_salereceipt_id_salereceipt_receipt_number_and_more'),
        ('client', '0002_bankaccount'),
        ('project', '0010_alter_paidexpenses_notes_and_more'),
        ('tax', '0005_salesgstreport_salesgstentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTds',
            fields=[
                ('key', models.AutoField(db_column='Sales_TDS_Key', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Sales_TDS_Date')),
                ('amount', models.DecimalField(db_column='Sales_TDS_Amount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], db_column='Sales_TDS_PaymentStatus', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Sales_TDS_CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Sales_TDS_UpdatedAt')),
                ('client', models.ForeignKey(db_column='Sales_TDS_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Sales_TDS_CompanyID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('customer', models.ForeignKey(db_column='Sales_TDS_CustKey', on_delete=django.db.models.deletion.CASCADE, to='sale.customer')),
                ('invoice', models.ForeignKey(db_column='Sales_TDS_InvoiceID', on_delete=django.db.models.deletion.CASCADE, to='sale.saleinvoice')),
                ('project', models.ForeignKey(db_column='Sales_TDS_ProjectID', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('unit', models.ForeignKey(db_column='Sales_TDS_UnitID', on_delete=django.db.models.deletion.CASCADE, to='project.projectunit')),
            ],
            options={
                'db_table': 'SalesTds',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='salestds',
            index=models.Index(fields=['client'], name='SalesTds_Sales_T_cad2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='salestds',
            index=models.Index(fields=['company'], name='SalesTds_Sales_T_bb65fe_idx'),
        ),
    ]
