# Generated by Django 4.0.5 on 2024-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='door_no',
            field=models.IntegerField(db_column='Proj_DoorNo', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plot_no',
            field=models.IntegerField(db_column='Proj_PlotNo', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='survey_no',
            field=models.IntegerField(db_column='Proj_SurveyNo', null=True),
        ),
    ]
