# Generated by Django 4.0.5 on 2024-08-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_door_no_project_plot_no_project_survey_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='id',
        ),
    ]
