# Generated by Django 4.0.5 on 2024-09-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projecttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='addr1',
            field=models.CharField(blank=True, db_column='Proj_Addr1', max_length=255, null=True),
        ),
    ]
