# Generated by Django 4.0.5 on 2024-09-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_vendorinvoice_invoice_status_and_more'),
        ('client', '0002_bankaccount'),
        ('project', '0004_alter_project_addr1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidExpenses',
            fields=[
                ('key', models.AutoField(db_column='PaidExpenses_Key', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='PaidExpenses_Date')),
                ('amount', models.IntegerField(db_column='PaidExpenses_Amount')),
                ('desc', models.CharField(db_column='PaidExpenses_Desc', max_length=100)),
                ('expense_type', models.CharField(blank=True, db_column='PaidExpenses_ExpenseType', max_length=100, null=True)),
                ('payment_desc', models.CharField(db_column='PaidExpenses_Payment_Desc', max_length=100)),
                ('client_id', models.ForeignKey(db_column='PaidExpenses_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='PaidExpenses_CompanyID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('payment_mode', models.ForeignKey(db_column='PaidExpenses_PaymentModeKey', on_delete=django.db.models.deletion.CASCADE, to='pricing.modeofpay')),
                ('project_key', models.ForeignKey(db_column='PaidExpenses_ProjectKey', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'PaidExpenses',
            },
        ),
    ]
