# Generated by Django 4.0.5 on 2024-10-17 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0005_paidexpenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidexpenses',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='paidexpenses',
            name='expense_type',
        ),
        migrations.AddField(
            model_name='paidexpenses',
            name='account_id',
            field=models.ForeignKey(blank=True, db_column='PaidExpenses_AccountID', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.bankaccount'),
        ),
        migrations.AlterField(
            model_name='paidexpenses',
            name='project_key',
            field=models.ForeignKey(blank=True, db_column='PaidExpenses_ProjectKey', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
