# Generated by Django 4.0.5 on 2024-10-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0006_remove_paidexpenses_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidexpenses',
            name='notes',
            field=models.CharField(blank=True, db_column='PaidExpenses_Notes', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('key', models.AutoField(db_column='ExpenseType_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='ExpenseType_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='ExpenseType_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='ExpenseType_Company_ID', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'db_table': 'ExpenseType',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='paidexpenses',
            name='expense_type',
            field=models.ForeignKey(db_column='PaidExpenses_ExpenseType', default=1, on_delete=django.db.models.deletion.CASCADE, to='project.expensetype'),
            preserve_default=False,
        ),
    ]
