# Generated by Django 4.0.5 on 2024-10-17 07:12

from django.db import migrations


def convert_extra_expense_amount_to_decimal(apps, schema_editor):
    PaidExpenses = apps.get_model(
        'project', 'PaidExpenses'
    )
    for obj in PaidExpenses.objects.all():
        obj.amount = float(obj.amount)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_paidexpenses_notes_expensetype_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_extra_expense_amount_to_decimal)
    ]
