# Generated by Django 4.0.5 on 2024-10-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_convert_amount_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidexpenses',
            name='amount',
            field=models.DecimalField(db_column='PaidExpenses_Amount', decimal_places=2, max_digits=10),
        ),
    ]
