# Generated by Django 4.0.5 on 2024-10-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_paidexpenses_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidexpenses',
            name='notes',
            field=models.CharField(blank=True, db_column='PaidExpenses_Notes', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paidexpenses',
            name='payment_desc',
            field=models.CharField(db_column='PaidExpenses_Payment_Desc', max_length=255),
        ),
    ]
