# Generated by Django 4.0.5 on 2024-11-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_paidexpenses_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='door_no',
            field=models.IntegerField(blank=True, db_column='Proj_DoorNo', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='plot_no',
            field=models.IntegerField(blank=True, db_column='Proj_PlotNo', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='survey_no',
            field=models.IntegerField(blank=True, db_column='Proj_SurveyNo', null=True),
        ),
    ]
