# Generated by Django 4.0.5 on 2024-12-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_door_no_alter_project_plot_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
    ]
