# Generated by Django 4.0.5 on 2025-03-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_project_unique_together_remove_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projtyp_key',
            field=models.ForeignKey(blank=True, db_column='Proj_ProjTyp_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projecttype'),
        ),
    ]
