# Generated by Django 4.0.5 on 2025-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_project_projtyp_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='car_parking_cost',
            field=models.DecimalField(blank=True, db_column='Proj_CarParkingCost', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='eb_cost',
            field=models.DecimalField(blank=True, db_column='Proj_EBCost', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='water_and_drainage_cost',
            field=models.DecimalField(blank=True, db_column='Proj_WaterAndDrainageCost', decimal_places=2, max_digits=12, null=True),
        ),
    ]
