# Generated by Django 4.0.5 on 2025-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_car_parking_cost_project_eb_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectunit',
            name='base_price',
            field=models.DecimalField(blank=True, db_column='ProjUnit_BasePrice', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projectunit',
            name='facing',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], db_column='ProjUnit_Facing', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='projectunit',
            name='gst_percentage',
            field=models.IntegerField(blank=True, db_column='ProjUnit_GSTPercentage', null=True),
        ),
    ]
