# Generated by Django 4.0.5 on 2025-03-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_projectunit_base_price_projectunit_facing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='arn',
            field=models.CharField(blank=True, db_column='Proj_ARN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='eb_service_no',
            field=models.BigIntegerField(blank=True, db_column='Proj_EBServiceNo', null=True),
        ),
    ]
