# Generated by Django 4.0.5 on 2025-03-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_project_arn_project_eb_service_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='eb_service_no',
        ),
    ]
