# Generated by Django 4.0.5 on 2025-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_project_eb_service_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='eb_service_no',
            field=models.CharField(blank=True, db_column='Proj_EBServiceNo', max_length=20, null=True),
        ),
    ]
