# Generated by Django 4.0.5 on 2025-04-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_project_eb_service_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidexpenses',
            name='payment_desc',
            field=models.CharField(blank=True, db_column='PaidExpenses_Payment_Desc', max_length=255, null=True),
        ),
    ]
