# Generated by Django 4.0.5 on 2025-05-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_paidexpenses_payment_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimageheader',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='projectimageheader',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='ProjectImageDetail',
        ),
        migrations.DeleteModel(
            name='ProjectImageHeader',
        ),
    ]
