# Generated by Django 4.0.5 on 2025-05-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0020_remove_projectimageheader_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectElevationDiagrams',
            fields=[
                ('key', models.AutoField(db_column='ProjElev_Key', primary_key=True, serialize=False)),
                ('image_url', models.TextField(db_column='ProjElev_ImgURL')),
                ('block_id', models.ForeignKey(db_column='ProjElev_Blk_Key', on_delete=django.db.models.deletion.CASCADE, related_name='elevation_diagrams', to='project.projectblock')),
                ('client_id', models.ForeignKey(db_column='ProjElev_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='ProjElev_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('project_id', models.ForeignKey(db_column='ProjElev_Proj_Key', on_delete=django.db.models.deletion.CASCADE, related_name='elevation_diagrams', to='project.project')),
            ],
            options={
                'db_table': 'ProjElevationDiagrams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project3DFloorPlans',
            fields=[
                ('key', models.AutoField(db_column='Proj3DFloor_Key', primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('3D', '3D'), ('FloorPlan', 'FloorPlan')], db_column='Proj3DFloor_ImageType', max_length=10)),
                ('image_url', models.TextField(db_column='Proj3DFloor_ImgURL')),
                ('block_id', models.ForeignKey(db_column='Proj3DFloor_Blk_Key', on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_images', to='project.projectblock')),
                ('client_id', models.ForeignKey(db_column='Proj3DFloor_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='Proj3DFloor_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('floor_id', models.ForeignKey(db_column='Proj3DFloor_Flr_Key', on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_images', to='project.projectfloor')),
                ('project_id', models.ForeignKey(db_column='Proj3DFloor_Proj_Key', on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_images', to='project.project')),
            ],
            options={
                'db_table': 'Project3DFloorPlans',
                'managed': True,
            },
        ),
    ]
