# Generated by Django 4.0.5 on 2025-05-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_projectelevationdiagrams_project3dfloorplans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project3DFloorPlans',
        ),
    ]
