# Generated by Django 4.0.5 on 2025-05-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0022_delete_project3dfloorplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project3DFloorPlanHdr',
            fields=[
                ('key', models.AutoField(db_column='Proj3DFloorHdr_Key', primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('3D', '3D'), ('FloorPlan', 'FloorPlan')], db_column='Proj3DFloorHdr_ImageType', max_length=10)),
                ('image_url', models.TextField(db_column='Proj3DFloorHdr_ImgURL')),
                ('block_id', models.ForeignKey(db_column='Proj3DFloorHdr_Blk_Key', on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_headers', to='project.projectblock')),
                ('client_id', models.ForeignKey(db_column='Proj3DFloorHdr_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='Proj3DFloorHdr_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('project_id', models.ForeignKey(db_column='Proj3DFloorHdr_Proj_Key', on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_headers', to='project.project')),
            ],
            options={
                'db_table': 'Project3DFloorPlanHdr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project3DFloorPlanDtl',
            fields=[
                ('key', models.AutoField(db_column='Proj3DFloorDtl_Key', primary_key=True, serialize=False)),
                ('floor_id', models.ForeignKey(db_column='Proj3DFloorDtl_Flr_Key', on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_details', to='project.projectfloor')),
                ('hdr_key', models.ForeignKey(db_column='Proj3DFloorDtl_Hdr_Key', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='project.project3dfloorplanhdr')),
            ],
            options={
                'db_table': 'Project3DFloorPlanDtl',
                'managed': True,
                'unique_together': {('hdr_key', 'floor_id')},
            },
        ),
    ]
