# Generated by Django 4.0.5 on 2025-05-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_project3dfloorplanhdr_project3dfloorplandtl'),
    ]

    operations = [
        migrations.AddField(
            model_name='project3dfloorplanhdr',
            name='image_name',
            field=models.CharField(blank=True, db_column='Proj3DFloorHdr_ImgName', max_length=255, null=True),
        ),
    ]
