# Generated by Django 4.0.5 on 2025-05-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0024_project3dfloorplanhdr_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUnitStatus',
            fields=[
                ('key', models.AutoField(db_column='ProjUnitStatus_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='ProjUnitStatus_Descr', max_length=100)),
                ('client_id', models.ForeignKey(db_column='ProjUnitStatus_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='ProjUnitStatus_Company_ID', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'db_table': 'ProjectUnitStatus',
                'managed': True,
            },
        ),
    ]
