# Generated by Django 4.0.5 on 2025-05-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_projectunitstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectunit',
            name='projunit_status_key',
            field=models.ForeignKey(blank=True, db_column='ProjUnit_Status_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projectunitstatus'),
        ),
    ]
