# Generated by Django 4.0.5 on 2025-06-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_projectunit_projunit_status_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetype',
            name='company_id',
        ),
    ]
