# Generated by Django 4.0.5 on 2025-05-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0026_projectunit_projunit_status_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together={('company', 'id')},
        ),
        migrations.RemoveField(
            model_name='projectstage',
            name='projwrk_key',
        ),
        migrations.DeleteModel(
            name='Projectwork',
        ),
    ]
