# Generated by Django 4.0.5 on 2025-05-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('estimate', '0001_initial'),
        ('project', '0027_alter_projectstage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWork',
            fields=[
                ('key', models.AutoField(db_column='ProjectWork_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ProjectWork_Name', max_length=255)),
                ('segment', models.CharField(db_column='ProjectWork_Sgmnt', max_length=255)),
                ('created_by', models.CharField(db_column='ProjectWork_CreatedBy', max_length=255)),
                ('createddttm', models.DateTimeField(auto_now_add=True, db_column='ProjectWork_CreatedDtTm')),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ProjectWork_LastModifiedBy', max_length=255, null=True)),
                ('lastmodifieddttm', models.DateTimeField(auto_now=True, db_column='ProjectWork_LastModifiedDtTm', null=True)),
                ('block_key', models.ForeignKey(db_column='ProjectWork_BlkKey', on_delete=django.db.models.deletion.CASCADE, to='project.projectblock')),
                ('category_key', models.ForeignKey(db_column='ProjectWork_CtgryKey', on_delete=django.db.models.deletion.CASCADE, to='estimate.workcategory')),
                ('client_id', models.ForeignKey(db_column='ProjectWork_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='ProjectWork_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('project_key', models.ForeignKey(db_column='ProjectWork_ProjKey', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('type_key', models.ForeignKey(db_column='ProjectWork_TypeKey', on_delete=django.db.models.deletion.CASCADE, to='estimate.worktype')),
            ],
            options={
                'db_table': 'ProjectWork',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='projwrk_key',
            field=models.ForeignKey(blank=True, db_column='ProjStg_ProjWrk_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projectwork'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together={('company', 'projwrk_key', 'id')},
        ),
    ]
