# Generated by Django 4.0.5 on 2025-07-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0027_remove_expensetype_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseVendor',
            fields=[
                ('key', models.AutoField(db_column='ExpenseVendor_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ExpenseVendor_Name', max_length=100)),
                ('client_id', models.ForeignKey(db_column='ExpenseVendor_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'ExpenseVendor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='paidexpenses',
            name='exp_vendor_id',
            field=models.ForeignKey(blank=True, db_column='PaidExpenses_ExpenseVendorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.expensevendor'),
        ),
    ]
