# Generated by Django 4.0.5 on 2025-06-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_remove_expensetype_company_id'),
        ('project', '0028_projectwork_alter_projectstage_unique_together_and_more'),
    ]

    operations = [
    ]
