# Generated by Django 4.0.5 on 2025-07-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_expensevendor_paidexpenses_exp_vendor_id'),
        ('project', '0029_merge_20250611_1152'),
    ]

    operations = [
    ]
