# Generated by Django 4.0.5 on 2025-07-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_merge_20250729_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sqftprice',
        ),
    ]
