# Generated by Django 4.0.5 on 2025-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_remove_project_sqftprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='builtuparea',
            field=models.DecimalField(blank=True, db_column='Proj_BuiltUpArea', decimal_places=2, max_digits=12, null=True),
        ),
    ]
