# Generated by Django 4.0.5 on 2025-08-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0032_project_builtuparea'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSchedule',
            fields=[
                ('key', models.AutoField(db_column='ProjectSchedule_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='ProjectSchedule_Name', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='ProjectSchedule_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='ProjectSchedule_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='ProjectSchedule_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='ProjectSchedule_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='ProjectSchedule_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('projtyp_key', models.ForeignKey(db_column='ProjectSchedule_ProjTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='project.projecttype')),
            ],
            options={
                'db_table': 'ProjectSchedule',
                'managed': True,
            },
        ),
    ]
