# Generated by Django 4.0.5 on 2025-08-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_projectschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectschedule',
            name='duration',
            field=models.IntegerField(db_column='ProjectSchedule_Duration', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectschedule',
            name='duration_type',
            field=models.CharField(choices=[('D', 'Days'), ('W', 'Weeks'), ('M', 'Months')], db_column='ProjectSchedule_DurationTyp', default='D', max_length=1),
            preserve_default=False,
        ),
    ]
