# Generated by Django 4.0.5 on 2025-10-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_projectschedule_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectblock',
            name='column_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_ColmnCount', null=True),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='floor_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_FlrCount', null=True),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='lift_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_LiftCount', null=True),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='ots_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_OtsCount', null=True),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='overhead_tank_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_OvrHdTnkCount', null=True),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='staircase_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_StrCaseCount', null=True),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='sump_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_SumpCount', null=True),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='unit_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_UnitCount', null=True),
        ),
    ]
