# Generated by Django 4.0.5 on 2025-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_projectblock_column_count_projectblock_floor_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfloor',
            name='no_of_units',
            field=models.CharField(blank=True, db_column='ProjFlr_NoOfUnits', max_length=100, null=True),
        ),
    ]
