# Generated by Django 4.0.5 on 2025-10-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_projectfloor_no_of_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectblock',
            name='floor_count',
        ),
    ]
