# Generated by Django 4.0.5 on 2025-10-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_remove_projectblock_floor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectblock',
            name='floor_count_abv_ground',
            field=models.IntegerField(blank=True, db_column='ProjBlk_FlrCount_AbvGrnd', null=True),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='floor_count_blw_ground',
            field=models.IntegerField(blank=True, db_column='ProjBlk_FlrCount_BlwGrnd', null=True),
        ),
    ]
