# Generated by Django 4.0.5 on 2025-11-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_projectblock_floor_count_abv_ground_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_of_blocks',
            field=models.CharField(blank=True, db_column='Proj_No_Of_Blocks', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='lift_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_LiftCount', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='ots_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_OtsCount', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='overhead_tank_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_OvrHdTnkCount', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='staircase_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_StrCaseCount', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='sump_count',
            field=models.IntegerField(blank=True, db_column='ProjBlk_SumpCount', default=1, null=True),
        ),
    ]
