# Generated by Django 4.0.5 on 2024-06-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('geolocation', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('key', models.AutoField(db_column='Cust_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='Cust_ID', max_length=30)),
                ('name', models.CharField(db_column='Cust_Name', max_length=100)),
                ('addr1', models.CharField(blank=True, db_column='Cust_Addr1', max_length=100, null=True)),
                ('addr2', models.CharField(blank=True, db_column='Cust_Addr2', max_length=100, null=True)),
                ('briefdescr', models.CharField(blank=True, db_column='Cust_BriefDescr', max_length=255, null=True)),
                ('createdby', models.CharField(blank=True, db_column='Cust_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='Cust_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='Cust_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='Cust_LastModifiedDtTm', null=True)),
                ('inactive', models.CharField(blank=True, db_column='Cust_InActive', max_length=1, null=True)),
                ('city_key', models.ForeignKey(db_column='Cust_City_Key', on_delete=django.db.models.deletion.CASCADE, to='geolocation.city')),
                ('client_id', models.ForeignKey(db_column='Cust_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Cust_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('state_key', models.ForeignKey(db_column='Cust_State_Key', on_delete=django.db.models.deletion.CASCADE, to='geolocation.state')),
            ],
            options={
                'db_table': 'Customer',
                'managed': True,
                'unique_together': {('company', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Salebooking',
            fields=[
                ('key', models.AutoField(db_column='SalBk_Key', primary_key=True, serialize=False)),
                ('docid', models.CharField(db_column='SalBk_DocID', max_length=3)),
                ('number', models.CharField(db_column='SalBk_Number', max_length=25)),
                ('date', models.DateField(db_column='SalBk_Date')),
                ('validtodate', models.DateField(db_column='SalBk_ValidToDate')),
                ('modeofpay', models.CharField(blank=True, db_column='SalBk_ModeOfPay', max_length=10, null=True)),
                ('saleamt', models.DecimalField(db_column='SalBk_SaleAmt', decimal_places=2, max_digits=15)),
                ('bookingamt', models.DecimalField(db_column='SalBk_BookingAmt', decimal_places=2, max_digits=15)),
                ('notes', models.CharField(blank=True, db_column='SalBk_Notes', max_length=255, null=True)),
                ('refnumber', models.CharField(blank=True, db_column='SalBk_RefNumber', max_length=25, null=True)),
                ('bankname', models.CharField(blank=True, db_column='SalBk_BankName', max_length=25, null=True)),
                ('chqdate', models.DateField(blank=True, db_column='SalBk_ChqDate', null=True)),
                ('chqstatus', models.CharField(blank=True, db_column='SalBk_ChqStatus', max_length=2, null=True)),
                ('docstatus', models.CharField(blank=True, db_column='SalBk_DocStatus', max_length=2, null=True)),
                ('submitteddttm', models.DateTimeField(blank=True, db_column='SalBk_SubmittedDtTm', null=True)),
                ('submittedby', models.CharField(blank=True, db_column='SalBk_SubmittedBy', max_length=100, null=True)),
                ('cancelleddttm', models.DateTimeField(blank=True, db_column='SalBk_CancelledDtTm', null=True)),
                ('cancelledby', models.CharField(blank=True, db_column='SalBk_CancelledBy', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='SalBk_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='SalBk_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='SalBk_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='SalBk_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='SalBk_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='SalBk_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('cust_key', models.ForeignKey(db_column='SalBk_Cust_Key', on_delete=django.db.models.deletion.CASCADE, to='sale.customer')),
                ('proj_key', models.ForeignKey(db_column='SalBk_Proj_Key', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('projunit_key', models.ForeignKey(db_column='SalBk_ProjUnit_Key', on_delete=django.db.models.deletion.CASCADE, to='project.projectunit')),
            ],
            options={
                'db_table': 'SaleBooking',
                'managed': True,
                'unique_together': {('company', 'docid', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Saleagreement',
            fields=[
                ('key', models.AutoField(db_column='SalAgr_Key', primary_key=True, serialize=False)),
                ('docid', models.CharField(db_column='SalAgr_DocID', max_length=3)),
                ('agreementno', models.CharField(db_column='SalAgr_AgreementNo', max_length=25)),
                ('agreementdate', models.DateField(db_column='SalAgr_AgreementDate')),
                ('saleamt', models.DecimalField(db_column='SalAgr_SaleAmt', decimal_places=2, max_digits=15)),
                ('notes', models.CharField(blank=True, db_column='SalAgr_Notes', max_length=255, null=True)),
                ('docstatus', models.CharField(blank=True, db_column='SalAgr_DocStatus', max_length=2, null=True)),
                ('submitteddttm', models.DateTimeField(blank=True, db_column='SalAgr_SubmittedDtTm', null=True)),
                ('submittedby', models.CharField(blank=True, db_column='SalAgr_SubmittedBy', max_length=100, null=True)),
                ('cancelleddttm', models.DateTimeField(blank=True, db_column='SalAgr_CancelledDtTm', null=True)),
                ('cancelledby', models.CharField(blank=True, db_column='SalAgr_CancelledBy', max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, db_column='SalAgr_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='SalAgr_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='SalAgr_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='SalAgr_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='SalAgr_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='SalAgr_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('cust_key', models.ForeignKey(db_column='SalAgr_Cust_Key', on_delete=django.db.models.deletion.CASCADE, to='sale.customer')),
                ('salbk_key', models.ForeignKey(db_column='SalAgr_SalBk_Key', on_delete=django.db.models.deletion.CASCADE, to='sale.salebooking')),
            ],
            options={
                'db_table': 'SaleAgreement',
                'managed': True,
                'unique_together': {('company', 'docid', 'agreementno')},
            },
        ),
        migrations.CreateModel(
            name='SaleagreementStages',
            fields=[
                ('key', models.AutoField(db_column='SalAgrStg_Key', primary_key=True, serialize=False)),
                ('item_descr', models.CharField(db_column='SalAgrStg_Item_Descr', max_length=100)),
                ('netamt', models.DecimalField(blank=True, db_column='SalAgrStg_NetAmt', decimal_places=2, max_digits=15, null=True)),
                ('invoiced', models.CharField(blank=True, db_column='SalAgrStg_Invoiced', max_length=1, null=True)),
                ('itemnotes', models.CharField(blank=True, db_column='SalAgrStg_ItemNotes', max_length=255, null=True)),
                ('createdby', models.CharField(blank=True, db_column='SalAgrStg_CreatedBy', max_length=100, null=True)),
                ('createddttm', models.DateTimeField(blank=True, db_column='SalAgrStg_CreatedDtTm', null=True)),
                ('lastmodifiedby', models.CharField(blank=True, db_column='SalAgrStg_LastModifiedBy', max_length=100, null=True)),
                ('lastmodifieddttm', models.DateTimeField(blank=True, db_column='SalAgrStg_LastModifiedDtTm', null=True)),
                ('client_id', models.ForeignKey(db_column='SalAgrStg_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company', models.ForeignKey(db_column='SalAgrStg_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('salagr_key', models.ForeignKey(db_column='SalAgrStg_SalAgr_Key', on_delete=django.db.models.deletion.CASCADE, to='sale.saleagreement')),
            ],
            options={
                'db_table': 'SaleAgreement_Stages',
                'managed': True,
                'unique_together': {('company', 'salagr_key', 'item_descr')},
            },
        ),
    ]
