# Generated by Django 4.0.5 on 2024-07-18 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='briefdescr',
        ),
        migrations.AddField(
            model_name='customer',
            name='aadhaar_no',
            field=models.IntegerField(db_column='Cust_AadhaarNo', default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(db_column='Cust_Age', default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(blank=True, db_column='Cust_ContactNo', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_id',
            field=models.CharField(blank=True, db_column='Cust_EmailID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_no',
            field=models.CharField(db_column='Cust_PanNo', default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(db_column='Cust_Sex', default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
