# Generated by Django 4.0.5 on 2024-07-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_remove_customer_briefdescr_customer_aadhaar_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company',
            new_name='company_id',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
