# Generated by Django 4.0.5 on 2024-07-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_rename_company_customer_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhaar_no',
            field=models.CharField(db_column='Cust_AadhaarNo', max_length=12),
        ),
    ]
