# Generated by Django 4.0.5 on 2024-07-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0001_initial'),
        ('sale', '0004_alter_customer_aadhaar_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAgreementPaymentSchedule',
            fields=[
                ('key', models.AutoField(db_column='SAPaymentScheduleKey', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='SAPaymentScheduleID', max_length=255)),
                ('payment_stage_desc', models.CharField(db_column='SAPaymentScheduleDesc', max_length=500)),
                ('amount', models.DecimalField(db_column='SAPaymentScheduleAmount', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'SaleAgreementPaymentSchedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SaleAgreementRateCard',
            fields=[
                ('key', models.AutoField(db_column='SARateCardKey', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='SARateCardID', max_length=30)),
                ('item_desc', models.CharField(db_column='SARateCardItemDesc', max_length=500)),
                ('rate', models.DecimalField(db_column='SARateCardRate', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'SaleAgreementRateCard',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='salebooking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salebooking',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='salebooking',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salebooking',
            name='cust_key',
        ),
        migrations.RemoveField(
            model_name='salebooking',
            name='proj_key',
        ),
        migrations.RemoveField(
            model_name='salebooking',
            name='projunit_key',
        ),
        migrations.AlterUniqueTogether(
            name='saleagreement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='saleagreement',
            name='agreement_date',
            field=models.DateField(db_column='SaleAgreementDate', default='2024-07-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleagreement',
            name='agreement_no',
            field=models.CharField(db_column='SaleAgreementNo', default=1001, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleagreement',
            name='company_id',
            field=models.ForeignKey(db_column='SaleAgreementCompanyID', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleagreement',
            name='customer_id',
            field=models.ForeignKey(db_column='SaleAgreementCustomerID', default=1, on_delete=django.db.models.deletion.CASCADE, to='sale.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleagreement',
            name='id',
            field=models.CharField(db_column='SaleAgreementID', default='SaleAgreement_1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleagreement',
            name='paid_amount',
            field=models.DecimalField(blank=True, db_column='SaleAgreementPaidAmount', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='saleagreement',
            name='project_id',
            field=models.ForeignKey(db_column='SaleAgreementProjectID', default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleagreement',
            name='sale_amount',
            field=models.DecimalField(blank=True, db_column='SaleAgreementSaleAmount', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='saleagreement',
            name='unit_id',
            field=models.ForeignKey(db_column='SaleAgreementUnitID', default=1, on_delete=django.db.models.deletion.CASCADE, to='project.projectunit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleagreement',
            name='client_id',
            field=models.ForeignKey(db_column='SaleAgreementClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase'),
        ),
        migrations.AlterField(
            model_name='saleagreement',
            name='key',
            field=models.AutoField(db_column='SaleAgreementKey', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleagreement',
            name='notes',
            field=models.TextField(blank=True, db_column='SaleAgreementNotes', null=True),
        ),
        migrations.DeleteModel(
            name='SaleagreementStages',
        ),
        migrations.AddField(
            model_name='saleagreementratecard',
            name='sale_agreement_id',
            field=models.ForeignKey(db_column='SARateCardAgreementID', on_delete=django.db.models.deletion.CASCADE, to='sale.saleagreement'),
        ),
        migrations.AddField(
            model_name='saleagreementpaymentschedule',
            name='sale_agreement_id',
            field=models.ForeignKey(db_column='SAPaymentScheduleAgreementID', on_delete=django.db.models.deletion.CASCADE, to='sale.saleagreement'),
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='agreementdate',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='agreementno',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='cancelledby',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='cancelleddttm',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='company',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='createddttm',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='cust_key',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='docid',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='docstatus',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='lastmodifiedby',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='lastmodifieddttm',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='salbk_key',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='saleamt',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='submittedby',
        ),
        migrations.RemoveField(
            model_name='saleagreement',
            name='submitteddttm',
        ),
        migrations.DeleteModel(
            name='Salebooking',
        ),
    ]
