# Generated by Django 4.0.5 on 2024-09-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_itemitemuom_createddttm_and_more'),
        ('project', '0005_paidexpenses'),
        ('client', '0002_bankaccount'),
        ('sale', '0005_saleagreementpaymentschedule_saleagreementratecard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchaseReceipt',
            fields=[
                ('key', models.AutoField(db_column='CustomerPurchRcpt_key', primary_key=True, serialize=False)),
                ('item_descr', models.CharField(db_column='CustomerPurchRcpt_ItemDesc', max_length=100)),
                ('vendor', models.CharField(db_column='CustomerPurchRcpt_Vendor', max_length=100)),
                ('amount', models.IntegerField(db_column='CustomerPurchRcpt_Amount')),
                ('builder_budget', models.IntegerField(db_column='CustomerPurchRcpt_BuilderBudget', null=True)),
                ('notes', models.CharField(db_column='CustomerPurchRcpt_Notes', max_length=100, null=True)),
                ('client_id', models.ForeignKey(db_column='CustomerPurchRcpt_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='CustomerPurchRcpt_CompanyID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('customer_key', models.ForeignKey(db_column='CustomerPurchRcpt_CustomerKey', on_delete=django.db.models.deletion.CASCADE, to='sale.customer')),
                ('project_key', models.ForeignKey(db_column='CustomerPurchRcpt_ProjKey', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('purpose_key', models.ForeignKey(db_column='CustomerPurchRcpt_PurposeKey', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purpose')),
            ],
            options={
                'db_table': 'Cusotmer_Purchase_Receipt',
            },
        ),
    ]
