# Generated by Django 4.0.5 on 2024-10-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_customerpurchasereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstnumber',
            field=models.CharField(blank=True, db_column='Cust_GSTNo', max_length=20, null=True),
        ),
    ]
