# Generated by Django 4.0.5 on 2024-11-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bankaccount'),
        ('project', '0010_alter_paidexpenses_notes_and_more'),
        ('sale', '0007_customer_gstnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('key', models.AutoField(db_column='SaleInvoiceKey', primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(db_column='SaleInvoice_InvoiceID', max_length=100, unique=True)),
                ('invoice_date', models.DateField(db_column='SaleInvoice_InvoiceDate')),
                ('invoice_amount', models.DecimalField(blank=True, db_column='SaleInvoice_InvoiceAmount', decimal_places=2, max_digits=15, null=True)),
                ('receivable_amount', models.DecimalField(blank=True, db_column='SaleInvoice_ReceivableAmount', decimal_places=2, max_digits=15, null=True)),
                ('paid_amount', models.DecimalField(blank=True, db_column='SaleInvoice_PaidAmount', decimal_places=2, max_digits=15, null=True)),
                ('tds_amount', models.DecimalField(blank=True, db_column='SaleInvoice_TDSAmount', decimal_places=2, max_digits=15, null=True)),
                ('gst_amount', models.DecimalField(blank=True, db_column='SaleInvoice_GSTAmount', decimal_places=2, max_digits=15, null=True)),
                ('invoice_status', models.CharField(choices=[('O', 'O'), ('P', 'P'), ('A', 'A')], db_column='SaleInvoice_InvoiceStatus', default='O', max_length=1)),
                ('notes', models.CharField(blank=True, db_column='SaleInvoice_Notes', max_length=500, null=True)),
                ('agreement_id', models.ForeignKey(blank=True, db_column='SaleInvoice_AgreementID', null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.saleagreement')),
                ('client_id', models.ForeignKey(db_column='SaleInvoice_ClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='SaleInvoice_CompanyID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('payment_schedule_id', models.ForeignKey(db_column='SaleInvoice_PaymentScheldueID', null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.saleagreementpaymentschedule')),
                ('project_id', models.ForeignKey(db_column='SaleInvoice_ProjectID', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'SaleInvoice',
                'managed': True,
            },
        ),
    ]
