# Generated by Django 4.0.5 on 2024-11-14 07:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_purchaseorder_discountamt_and_more'),
        ('client', '0002_bankaccount'),
        ('project', '0010_alter_paidexpenses_notes_and_more'),
        ('sale', '0008_saleinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOfFund',
            fields=[
                ('key', models.AutoField(db_column='SourceOfFund_Key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='SourceOfFund_Name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'SourceOfFund',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='receivable_amount',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='tds_amount',
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='is_tds_invoice',
            field=models.BooleanField(db_column='SaleInvoice_IsTDS', default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SaleReceipt',
            fields=[
                ('key', models.AutoField(db_column='Sale_Receipt_Key', primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='Sale_Receipt_ID')),
                ('date', models.DateField(db_column='Sale_Receipt_Date')),
                ('amount', models.DecimalField(db_column='Sale_Receipt_Amount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transaction_detail', models.CharField(blank=True, db_column='Sale_Receipt_TransactionDetail', max_length=255, null=True)),
                ('notes', models.CharField(blank=True, db_column='Sale_Receipt_Notes', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Sale_Receipt_CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Sale_Receipt_UpdatedAt')),
                ('account_id', models.ForeignKey(blank=True, db_column='Sale_Receipt_AccountID', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.bankaccount')),
                ('client', models.ForeignKey(db_column='Sale_Receipt_ClientID', on_delete=django.db.models.deletion.CASCADE, related_name='sale_receipts', to='client.clientbase')),
                ('company', models.ForeignKey(db_column='Sale_Receipt_CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='sale_receipts', to='client.company')),
                ('customer_id', models.ForeignKey(db_column='Sale_Receipt_CustID', on_delete=django.db.models.deletion.CASCADE, related_name='sale_receipts', to='sale.customer')),
                ('invoice_id', models.ForeignKey(db_column='Sale_Receipt_InvoiceID', on_delete=django.db.models.deletion.CASCADE, to='sale.saleinvoice')),
                ('payment_mode_id', models.ForeignKey(db_column='Sale_Receipt_PaymentModeID', on_delete=django.db.models.deletion.CASCADE, to='pricing.modeofpay')),
                ('project_id', models.ForeignKey(db_column='Sale_Receipt_ProjectID', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('source_of_fund_id', models.ForeignKey(db_column='Sale_Receipt_SourceOfFundID', on_delete=django.db.models.deletion.CASCADE, to='sale.sourceoffund')),
                ('unit_id', models.ForeignKey(db_column='Sale_Receipt_UnitID', on_delete=django.db.models.deletion.CASCADE, to='project.projectunit')),
            ],
            options={
                'db_table': 'SaleReceipt',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='salereceipt',
            index=models.Index(fields=['date'], name='SaleReceipt_Sale_Re_23cc68_idx'),
        ),
        migrations.AddIndex(
            model_name='salereceipt',
            index=models.Index(fields=['client'], name='SaleReceipt_Sale_Re_c30c90_idx'),
        ),
        migrations.AddIndex(
            model_name='salereceipt',
            index=models.Index(fields=['company'], name='SaleReceipt_Sale_Re_ee45cf_idx'),
        ),
    ]
