# Generated by Django 4.0.5 on 2024-11-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_sourceoffund_remove_saleinvoice_receivable_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salereceipt',
            name='id',
        ),
        migrations.AddField(
            model_name='salereceipt',
            name='receipt_number',
            field=models.IntegerField(db_column='Sale_Receipt_ReceiptNumber', default=1001),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='date',
            field=models.DateField(auto_now_add=True, db_column='Sale_Receipt_Date'),
        ),
    ]
