# Generated by Django 4.0.5 on 2024-11-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_remove_salereceipt_id_salereceipt_receipt_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='gstnumber',
            new_name='gst_no',
        ),
    ]
