# Generated by Django 4.0.5 on 2024-11-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_rename_gstnumber_customer_gst_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchasereceipt',
            name='notes',
            field=models.CharField(blank=True, db_column='CustomerPurchRcpt_Notes', max_length=100, null=True),
        ),
    ]
