# Generated by Django 4.0.5 on 2025-02-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0013_alter_customerpurchasereceipt_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereceipt',
            name='date',
            field=models.DateField(db_column='Sale_Receipt_Date'),
        ),
    ]
