# Generated by Django 4.0.5 on 2025-04-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0014_alter_salereceipt_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerpurchasereceipt',
            table='Customer_Purchase_Receipt',
        ),
    ]
