# Generated by Django 4.0.5 on 2025-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0015_alter_customerpurchasereceipt_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleagreement',
            name='agreement_no',
            field=models.CharField(db_column='SaleAgreementNo', max_length=100),
        ),
    ]
