# Generated by Django 4.0.5 on 2025-07-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0016_alter_saleagreement_agreement_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='invoice_id',
            field=models.CharField(db_column='SaleInvoice_InvoiceID', max_length=100),
        ),
    ]
