# Generated by Django 4.0.5 on 2025-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0017_alter_saleinvoice_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleagreementpaymentschedule',
            name='stage_status',
            field=models.CharField(choices=[('O', 'O'), ('I', 'I')], db_column='SAPaymentScheduleStatus', default='O', max_length=1),
        ),
    ]
