# Generated by Django 4.0.5 on 2024-07-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0005_saleagreementpaymentschedule_saleagreementratecard_and_more'),
        ('project', '0001_initial'),
        ('inventory', '0001_initial'),
        ('client', '0002_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionAgreement',
            fields=[
                ('key', models.AutoField(db_column='ConstructionAgreementKey', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='ConstructionAgreementID', max_length=30)),
                ('agreement_no', models.CharField(db_column='ConstructionAgreementNo', max_length=100, unique=True)),
                ('agreement_date', models.DateField(db_column='ConstructionAgreementDate')),
                ('contract_amount', models.DecimalField(blank=True, db_column='ConstructionAgreementContractAmount', decimal_places=2, max_digits=15, null=True)),
                ('paid_amount', models.DecimalField(blank=True, db_column='ConstructionAgreementPaidAmount', decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, db_column='ConstructionAgreementNotes', null=True)),
                ('client_id', models.ForeignKey(db_column='ConstructionAgreementClientID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='ConstructionAgreementCompanyID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('customer_id', models.ForeignKey(db_column='ConstructionAgreementCustomerID', on_delete=django.db.models.deletion.CASCADE, to='sale.customer')),
                ('project_id', models.ForeignKey(db_column='ConstructionAgreementProjectID', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('unit_id', models.ForeignKey(db_column='ConstructionAgreementUnitID', on_delete=django.db.models.deletion.CASCADE, to='project.projectunit')),
            ],
            options={
                'db_table': 'ConstructionAgreement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstructionAgreementService',
            fields=[
                ('key', models.AutoField(db_column='CAServiceKey', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='CAServiceID', max_length=30)),
                ('service_desc', models.CharField(db_column='CAServiceDesc', max_length=500)),
                ('quantity', models.IntegerField(db_column='CAServiceQuantity')),
                ('rate_per_unit', models.DecimalField(db_column='CAServiceRatePerUnit', decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(db_column='CAServiceCost', decimal_places=2, max_digits=10)),
                ('construction_agreement_id', models.ForeignKey(db_column='CAServiceAgreementID', on_delete=django.db.models.deletion.CASCADE, to='construction.constructionagreement')),
                ('uom', models.ForeignKey(db_column='CAServiceUOMID', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemuom')),
            ],
            options={
                'db_table': 'ConstructionAgreementService',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstructionAgreementPaymentSchedule',
            fields=[
                ('key', models.AutoField(db_column='CAPaymentScheduleKey', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='CAPaymentScheduleID', max_length=255)),
                ('payment_stage_desc', models.CharField(db_column='CAPaymentScheduleDesc', max_length=500)),
                ('amount', models.DecimalField(db_column='CAPaymentScheduleAmount', decimal_places=2, max_digits=10)),
                ('construction_agreement_id', models.ForeignKey(db_column='CAPaymentScheduleAgreementID', on_delete=django.db.models.deletion.CASCADE, to='construction.constructionagreement')),
            ],
            options={
                'db_table': 'ConstructionAgreementPaymentSchedule',
                'managed': True,
            },
        ),
    ]
