# Generated by Django 4.0.5 on 2024-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionagreementservice',
            name='cost',
        ),
        migrations.AddField(
            model_name='constructionagreementservice',
            name='amount',
            field=models.DecimalField(db_column='CAServiceAmount', decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
    ]
