# Generated by Django 4.0.5 on 2024-06-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('client', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourType',
            fields=[
                ('key', models.AutoField(db_column='LabourType_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='LabourType_Id', max_length=30)),
                ('name', models.CharField(db_column='LabourType_Name', max_length=300)),
                ('client_id', models.ForeignKey(db_column='LabTrack_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='LabTrack_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('itemtyp_key', models.ForeignKey(db_column='LabourType_ItemTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
            ],
            options={
                'db_table': 'LabourType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DailyLabourTracker',
            fields=[
                ('key', models.AutoField(db_column='LabTrack_Key', primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, db_column='LabTrack_Id', max_length=30, null=True)),
                ('task', models.CharField(blank=True, db_column='LabTrack_Task', max_length=50, null=True)),
                ('completion', models.CharField(blank=True, db_column='LabTrack_Completion', max_length=50, null=True)),
                ('labourdetails', models.CharField(db_column='LabTrack_Labour_Details', max_length=10000)),
                ('overallcount', models.IntegerField(blank=True, db_column='LabTrack_Overall_Count', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='LabTrack_Updated_By', max_length=30, null=True)),
                ('comments', models.CharField(blank=True, db_column='LabTrack_Comments', max_length=100, null=True)),
                ('last_updated_time', models.DateTimeField(blank=True, db_column='LabTrack_Last_Updated_Time', null=True)),
                ('client_id', models.ForeignKey(db_column='LabTrack_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='LabTrack_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('itemtyp_key', models.ForeignKey(db_column='LabTrack_ItemTyp_Key', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
                ('project', models.ForeignKey(blank=True, db_column='LabTrack_Project', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'daily_labour_tracker',
                'managed': True,
            },
        ),
    ]
