# Generated by Django 4.0.5 on 2025-08-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourtype',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='labourtype',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='labourtype',
            name='itemtyp_key',
        ),
        migrations.DeleteModel(
            name='DailyLabourTracker',
        ),
        migrations.DeleteModel(
            name='LabourType',
        ),
    ]
