# Generated by Django 4.0.5 on 2025-08-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_bankaccount'),
        ('estimate', '0001_initial'),
        ('project', '0032_project_builtuparea'),
        ('daily_tracker', '0002_remove_labourtype_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkProgressDtl',
            fields=[
                ('key', models.AutoField(db_column='DailyWrkProgressDtl_Key', primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='DailyWrkProgressDtl_Descr', max_length=255)),
                ('comments', models.CharField(blank=True, db_column='DailyWrkProgressDtl_Cmnts', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Y', 'Yet to start'), ('P', 'In progress'), ('C', 'Completed')], db_column='DailyWrkProgressDtl_Status', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='DailyWrkProgressDtl_CreatedAt')),
                ('created_by', models.CharField(db_column='DailyWrkProgressDtl_CreatedBy', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='DailyWrkProgressDtl_UpdatedAt', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='DailyWrkProgressDtl_UpdatedBy', max_length=255, null=True)),
                ('client_id', models.ForeignKey(db_column='DailyWrkProgressDtl_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
            ],
            options={
                'db_table': 'DailyWorkProgressDtl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DailyWorkProgressImage',
            fields=[
                ('key', models.AutoField(db_column='DailyWrkProgressImage_Key', primary_key=True, serialize=False)),
                ('image_url', models.TextField(db_column='DailyWrkProgressImage_URL')),
                ('caption', models.CharField(blank=True, db_column='DailyWrkProgressImage_Caption', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='DailyWrkProgressImage_CreatedAt')),
                ('created_by', models.CharField(db_column='DailyWrkProgressImage_CreatedBy', max_length=255)),
                ('client_id', models.ForeignKey(db_column='DailyWrkProgressImage_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('dtl_key', models.ForeignKey(db_column='DailyWrkProgressImage_Dtl_Key', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='daily_tracker.dailyworkprogressdtl')),
            ],
            options={
                'db_table': 'DailyWorkProgressImage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DailyWorkProgressHdr',
            fields=[
                ('key', models.AutoField(db_column='DailyWrkProgressHdr_Key', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Y', 'Yet to start'), ('P', 'In progress'), ('C', 'Completed')], db_column='DailyWrkProgressHdr_Status', max_length=1)),
                ('date', models.DateField(db_column='DailyWrkProgressHdr_Date', db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='DailyWrkProgressHdr_CreatedAt')),
                ('created_by', models.CharField(db_column='DailyWrkProgressHdr_CreatedBy', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='DailyWrkProgressHdr_UpdatedAt', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='DailyWrkProgressHdr_UpdatedBy', max_length=255, null=True)),
                ('blk_key', models.ForeignKey(db_column='DailyWrkProgressHdr_Blk_Key', on_delete=django.db.models.deletion.CASCADE, to='project.projectblock')),
                ('client_id', models.ForeignKey(db_column='DailyWrkProgressHdr_Client_ID', on_delete=django.db.models.deletion.CASCADE, to='client.clientbase')),
                ('company_id', models.ForeignKey(db_column='DailyWrkProgressHdr_Company_ID', on_delete=django.db.models.deletion.CASCADE, to='client.company')),
                ('floor_key', models.ForeignKey(db_column='DailyWrkProgressHdr_Flr_Key', on_delete=django.db.models.deletion.CASCADE, to='project.projectfloor')),
                ('project_key', models.ForeignKey(db_column='DailyWrkProgressHdr_Proj_Key', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('unit_key', models.ForeignKey(db_column='DailyWrkProgressHdr_Unit_Key', on_delete=django.db.models.deletion.CASCADE, to='project.projectunit')),
                ('workctgry_key', models.ForeignKey(db_column='DailyWrkProgressHdr_WrkCtgry_Key', on_delete=django.db.models.deletion.CASCADE, to='estimate.workcategory')),
            ],
            options={
                'db_table': 'DailyWorkProgressHdr',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='dailyworkprogressdtl',
            name='hdr_key',
            field=models.ForeignKey(db_column='DailyWrkProgressDtl_Hdr_Key', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='daily_tracker.dailyworkprogresshdr'),
        ),
    ]
