# Generated by Django 4.0.5 on 2025-08-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_projectschedule_duration_and_more'),
        ('daily_tracker', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkprogresshdr',
            name='schedule_key',
            field=models.ForeignKey(blank=True, db_column='DailyWrkProgressHdr_Schdle_Key', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projectschedule'),
        ),
    ]
