# Generated by Django 4.0.5 on 2025-09-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tracker', '0004_dailyworkprogresshdr_schedule_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkprogressimage',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='DailyWrkProgressImage_CreatedAt', null=True),
        ),
    ]
